//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AcceptCallingOfferResultState.
const (
	AcceptCallingOfferResultStateCONNECTED        AcceptCallingOfferResultState = "CONNECTED"
	AcceptCallingOfferResultStateCONNECTING       AcceptCallingOfferResultState = "CONNECTING"
	AcceptCallingOfferResultStateFOLLOWUPREQUIRED AcceptCallingOfferResultState = "FOLLOW_UP_REQUIRED"
	AcceptCallingOfferResultStateNEEDSDISPOSITION AcceptCallingOfferResultState = "NEEDS_DISPOSITION"
	AcceptCallingOfferResultStateOFFERING         AcceptCallingOfferResultState = "OFFERING"
	AcceptCallingOfferResultStateRECONCILING      AcceptCallingOfferResultState = "RECONCILING"
	AcceptCallingOfferResultStateRESOLVED         AcceptCallingOfferResultState = "RESOLVED"
	AcceptCallingOfferResultStateUNANSWERED       AcceptCallingOfferResultState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the AcceptCallingOfferResultState enum.
func (e AcceptCallingOfferResultState) Valid() bool {
	switch e {
	case AcceptCallingOfferResultStateCONNECTED:
		return true
	case AcceptCallingOfferResultStateCONNECTING:
		return true
	case AcceptCallingOfferResultStateFOLLOWUPREQUIRED:
		return true
	case AcceptCallingOfferResultStateNEEDSDISPOSITION:
		return true
	case AcceptCallingOfferResultStateOFFERING:
		return true
	case AcceptCallingOfferResultStateRECONCILING:
		return true
	case AcceptCallingOfferResultStateRESOLVED:
		return true
	case AcceptCallingOfferResultStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for AcceptCallingOfferResultStatus.
const (
	ACCEPTED       AcceptCallingOfferResultStatus = "ACCEPTED"
	ALREADYCLAIMED AcceptCallingOfferResultStatus = "ALREADY_CLAIMED"
	EXPIRED        AcceptCallingOfferResultStatus = "EXPIRED"
	INELIGIBLE     AcceptCallingOfferResultStatus = "INELIGIBLE"
)

// Valid indicates whether the value is a known member of the AcceptCallingOfferResultStatus enum.
func (e AcceptCallingOfferResultStatus) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case ALREADYCLAIMED:
		return true
	case EXPIRED:
		return true
	case INELIGIBLE:
		return true
	default:
		return false
	}
}

// Defines values for ActorType.
const (
	ActorTypeHUMAN            ActorType = "HUMAN"
	ActorTypePLATFORMOPERATOR ActorType = "PLATFORM_OPERATOR"
)

// Valid indicates whether the value is a known member of the ActorType enum.
func (e ActorType) Valid() bool {
	switch e {
	case ActorTypeHUMAN:
		return true
	case ActorTypePLATFORMOPERATOR:
		return true
	default:
		return false
	}
}

// Defines values for CallHistoryItemDirection.
const (
	INBOUND CallHistoryItemDirection = "INBOUND"
)

// Valid indicates whether the value is a known member of the CallHistoryItemDirection enum.
func (e CallHistoryItemDirection) Valid() bool {
	switch e {
	case INBOUND:
		return true
	default:
		return false
	}
}

// Defines values for CallHistoryItemOutcome.
const (
	CallHistoryItemOutcomeCONNECTED        CallHistoryItemOutcome = "CONNECTED"
	CallHistoryItemOutcomeCONNECTING       CallHistoryItemOutcome = "CONNECTING"
	CallHistoryItemOutcomeFOLLOWUPREQUIRED CallHistoryItemOutcome = "FOLLOW_UP_REQUIRED"
	CallHistoryItemOutcomeNEEDSDISPOSITION CallHistoryItemOutcome = "NEEDS_DISPOSITION"
	CallHistoryItemOutcomeOFFERING         CallHistoryItemOutcome = "OFFERING"
	CallHistoryItemOutcomeRECONCILING      CallHistoryItemOutcome = "RECONCILING"
	CallHistoryItemOutcomeRESOLVED         CallHistoryItemOutcome = "RESOLVED"
	CallHistoryItemOutcomeUNANSWERED       CallHistoryItemOutcome = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the CallHistoryItemOutcome enum.
func (e CallHistoryItemOutcome) Valid() bool {
	switch e {
	case CallHistoryItemOutcomeCONNECTED:
		return true
	case CallHistoryItemOutcomeCONNECTING:
		return true
	case CallHistoryItemOutcomeFOLLOWUPREQUIRED:
		return true
	case CallHistoryItemOutcomeNEEDSDISPOSITION:
		return true
	case CallHistoryItemOutcomeOFFERING:
		return true
	case CallHistoryItemOutcomeRECONCILING:
		return true
	case CallHistoryItemOutcomeRESOLVED:
		return true
	case CallHistoryItemOutcomeUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for CallHistoryItemType.
const (
	CALL CallHistoryItemType = "CALL"
)

// Valid indicates whether the value is a known member of the CallHistoryItemType enum.
func (e CallHistoryItemType) Valid() bool {
	switch e {
	case CALL:
		return true
	default:
		return false
	}
}

// Defines values for CallingCallState.
const (
	CallingCallStateCONNECTED        CallingCallState = "CONNECTED"
	CallingCallStateCONNECTING       CallingCallState = "CONNECTING"
	CallingCallStateFOLLOWUPREQUIRED CallingCallState = "FOLLOW_UP_REQUIRED"
	CallingCallStateNEEDSDISPOSITION CallingCallState = "NEEDS_DISPOSITION"
	CallingCallStateRECONCILING      CallingCallState = "RECONCILING"
	CallingCallStateRESOLVED         CallingCallState = "RESOLVED"
	CallingCallStateUNANSWERED       CallingCallState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the CallingCallState enum.
func (e CallingCallState) Valid() bool {
	switch e {
	case CallingCallStateCONNECTED:
		return true
	case CallingCallStateCONNECTING:
		return true
	case CallingCallStateFOLLOWUPREQUIRED:
		return true
	case CallingCallStateNEEDSDISPOSITION:
		return true
	case CallingCallStateRECONCILING:
		return true
	case CallingCallStateRESOLVED:
		return true
	case CallingCallStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for CallingDispositionRequestOutcome.
const (
	CallingDispositionRequestOutcomeFOLLOWUPREQUIRED CallingDispositionRequestOutcome = "FOLLOW_UP_REQUIRED"
	CallingDispositionRequestOutcomeRESOLVED         CallingDispositionRequestOutcome = "RESOLVED"
)

// Valid indicates whether the value is a known member of the CallingDispositionRequestOutcome enum.
func (e CallingDispositionRequestOutcome) Valid() bool {
	switch e {
	case CallingDispositionRequestOutcomeFOLLOWUPREQUIRED:
		return true
	case CallingDispositionRequestOutcomeRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for CallingOfferState.
const (
	CallingOfferStateOFFERING CallingOfferState = "OFFERING"
)

// Valid indicates whether the value is a known member of the CallingOfferState enum.
func (e CallingOfferState) Valid() bool {
	switch e {
	case CallingOfferStateOFFERING:
		return true
	default:
		return false
	}
}

// Defines values for CallingRecordingState.
const (
	FAILED    CallingRecordingState = "FAILED"
	INTENDED  CallingRecordingState = "INTENDED"
	READY     CallingRecordingState = "READY"
	RECORDING CallingRecordingState = "RECORDING"
)

// Valid indicates whether the value is a known member of the CallingRecordingState enum.
func (e CallingRecordingState) Valid() bool {
	switch e {
	case FAILED:
		return true
	case INTENDED:
		return true
	case READY:
		return true
	case RECORDING:
		return true
	default:
		return false
	}
}

// Defines values for CreateStaffTaskRequestSource.
const (
	Agent CreateStaffTaskRequestSource = "agent"
)

// Valid indicates whether the value is a known member of the CreateStaffTaskRequestSource enum.
func (e CreateStaffTaskRequestSource) Valid() bool {
	switch e {
	case Agent:
		return true
	default:
		return false
	}
}

// Defines values for HealthRole.
const (
	PortalApi       HealthRole = "portal-api"
	ProviderIngress HealthRole = "provider-ingress"
	Realtime        HealthRole = "realtime"
)

// Valid indicates whether the value is a known member of the HealthRole enum.
func (e HealthRole) Valid() bool {
	switch e {
	case PortalApi:
		return true
	case ProviderIngress:
		return true
	case Realtime:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewKind.
const (
	InvitationPreviewKindPLATFORMOPERATOR   InvitationPreviewKind = "PLATFORM_OPERATOR"
	InvitationPreviewKindPRACTICEINVITATION InvitationPreviewKind = "PRACTICE_INVITATION"
)

// Valid indicates whether the value is a known member of the InvitationPreviewKind enum.
func (e InvitationPreviewKind) Valid() bool {
	switch e {
	case InvitationPreviewKindPLATFORMOPERATOR:
		return true
	case InvitationPreviewKindPRACTICEINVITATION:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewLocationScope.
const (
	InvitationPreviewLocationScopeALL      InvitationPreviewLocationScope = "ALL"
	InvitationPreviewLocationScopeSELECTED InvitationPreviewLocationScope = "SELECTED"
)

// Valid indicates whether the value is a known member of the InvitationPreviewLocationScope enum.
func (e InvitationPreviewLocationScope) Valid() bool {
	switch e {
	case InvitationPreviewLocationScopeALL:
		return true
	case InvitationPreviewLocationScopeSELECTED:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewRole.
const (
	InvitationPreviewRoleADMIN InvitationPreviewRole = "ADMIN"
	InvitationPreviewRoleSTAFF InvitationPreviewRole = "STAFF"
)

// Valid indicates whether the value is a known member of the InvitationPreviewRole enum.
func (e InvitationPreviewRole) Valid() bool {
	switch e {
	case InvitationPreviewRoleADMIN:
		return true
	case InvitationPreviewRoleSTAFF:
		return true
	default:
		return false
	}
}

// Defines values for MembershipLocationScope.
const (
	MembershipLocationScopeALL      MembershipLocationScope = "ALL"
	MembershipLocationScopeSELECTED MembershipLocationScope = "SELECTED"
)

// Valid indicates whether the value is a known member of the MembershipLocationScope enum.
func (e MembershipLocationScope) Valid() bool {
	switch e {
	case MembershipLocationScopeALL:
		return true
	case MembershipLocationScopeSELECTED:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRole.
const (
	MembershipRoleADMIN MembershipRole = "ADMIN"
	MembershipRoleSTAFF MembershipRole = "STAFF"
)

// Valid indicates whether the value is a known member of the MembershipRole enum.
func (e MembershipRole) Valid() bool {
	switch e {
	case MembershipRoleADMIN:
		return true
	case MembershipRoleSTAFF:
		return true
	default:
		return false
	}
}

// Defines values for NavigationItemId.
const (
	CallCenter NavigationItemId = "call-center"
	Recordings NavigationItemId = "recordings"
	Settings   NavigationItemId = "settings"
	Tasks      NavigationItemId = "tasks"
)

// Valid indicates whether the value is a known member of the NavigationItemId enum.
func (e NavigationItemId) Valid() bool {
	switch e {
	case CallCenter:
		return true
	case Recordings:
		return true
	case Settings:
		return true
	case Tasks:
		return true
	default:
		return false
	}
}

// Defines values for OperatorCallingTimelineState.
const (
	OperatorCallingTimelineStateCONNECTED        OperatorCallingTimelineState = "CONNECTED"
	OperatorCallingTimelineStateCONNECTING       OperatorCallingTimelineState = "CONNECTING"
	OperatorCallingTimelineStateFOLLOWUPREQUIRED OperatorCallingTimelineState = "FOLLOW_UP_REQUIRED"
	OperatorCallingTimelineStateNEEDSDISPOSITION OperatorCallingTimelineState = "NEEDS_DISPOSITION"
	OperatorCallingTimelineStateOFFERING         OperatorCallingTimelineState = "OFFERING"
	OperatorCallingTimelineStateRECONCILING      OperatorCallingTimelineState = "RECONCILING"
	OperatorCallingTimelineStateRESOLVED         OperatorCallingTimelineState = "RESOLVED"
	OperatorCallingTimelineStateUNANSWERED       OperatorCallingTimelineState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the OperatorCallingTimelineState enum.
func (e OperatorCallingTimelineState) Valid() bool {
	switch e {
	case OperatorCallingTimelineStateCONNECTED:
		return true
	case OperatorCallingTimelineStateCONNECTING:
		return true
	case OperatorCallingTimelineStateFOLLOWUPREQUIRED:
		return true
	case OperatorCallingTimelineStateNEEDSDISPOSITION:
		return true
	case OperatorCallingTimelineStateOFFERING:
		return true
	case OperatorCallingTimelineStateRECONCILING:
		return true
	case OperatorCallingTimelineStateRESOLVED:
		return true
	case OperatorCallingTimelineStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for ProviderReceiptRecoveryState.
const (
	PENDING ProviderReceiptRecoveryState = "PENDING"
)

// Valid indicates whether the value is a known member of the ProviderReceiptRecoveryState enum.
func (e ProviderReceiptRecoveryState) Valid() bool {
	switch e {
	case PENDING:
		return true
	default:
		return false
	}
}

// Defines values for StaffTaskCategory.
const (
	Appointments  StaffTaskCategory = "appointments"
	Billing       StaffTaskCategory = "billing"
	Documentation StaffTaskCategory = "documentation"
	Medication    StaffTaskCategory = "medication"
	Optical       StaffTaskCategory = "optical"
	Other         StaffTaskCategory = "other"
	Referrals     StaffTaskCategory = "referrals"
)

// Valid indicates whether the value is a known member of the StaffTaskCategory enum.
func (e StaffTaskCategory) Valid() bool {
	switch e {
	case Appointments:
		return true
	case Billing:
		return true
	case Documentation:
		return true
	case Medication:
		return true
	case Optical:
		return true
	case Other:
		return true
	case Referrals:
		return true
	default:
		return false
	}
}

// Defines values for StaffTaskReceiptStatus.
const (
	Created   StaffTaskReceiptStatus = "created"
	Duplicate StaffTaskReceiptStatus = "duplicate"
)

// Valid indicates whether the value is a known member of the StaffTaskReceiptStatus enum.
func (e StaffTaskReceiptStatus) Valid() bool {
	switch e {
	case Created:
		return true
	case Duplicate:
		return true
	default:
		return false
	}
}

// Defines values for StaffTaskUrgency.
const (
	HighPriority StaffTaskUrgency = "high_priority"
	NonUrgent    StaffTaskUrgency = "non_urgent"
	Normal       StaffTaskUrgency = "normal"
)

// Valid indicates whether the value is a known member of the StaffTaskUrgency enum.
func (e StaffTaskUrgency) Valid() bool {
	switch e {
	case HighPriority:
		return true
	case NonUrgent:
		return true
	case Normal:
		return true
	default:
		return false
	}
}

// Defines values for TaskOrigin.
const (
	ABITAAI           TaskOrigin = "ABITA_AI"
	HUMANCALLFOLLOWUP TaskOrigin = "HUMAN_CALL_FOLLOW_UP"
)

// Valid indicates whether the value is a known member of the TaskOrigin enum.
func (e TaskOrigin) Valid() bool {
	switch e {
	case ABITAAI:
		return true
	case HUMANCALLFOLLOWUP:
		return true
	default:
		return false
	}
}

// Defines values for TaskState.
const (
	COMPLETED TaskState = "COMPLETED"
	OPEN      TaskState = "OPEN"
)

// Valid indicates whether the value is a known member of the TaskState enum.
func (e TaskState) Valid() bool {
	switch e {
	case COMPLETED:
		return true
	case OPEN:
		return true
	default:
		return false
	}
}

// Defines values for TaskActorKind.
const (
	TaskActorKindHUMAN   TaskActorKind = "HUMAN"
	TaskActorKindSERVICE TaskActorKind = "SERVICE"
)

// Valid indicates whether the value is a known member of the TaskActorKind enum.
func (e TaskActorKind) Valid() bool {
	switch e {
	case TaskActorKindHUMAN:
		return true
	case TaskActorKindSERVICE:
		return true
	default:
		return false
	}
}

// Defines values for TaskQueryRequestOrdering.
const (
	Priority TaskQueryRequestOrdering = "priority"
	Time     TaskQueryRequestOrdering = "time"
)

// Valid indicates whether the value is a known member of the TaskQueryRequestOrdering enum.
func (e TaskQueryRequestOrdering) Valid() bool {
	switch e {
	case Priority:
		return true
	case Time:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSnapshotSchemaVersion.
const (
	N20260724 WorkspaceSnapshotSchemaVersion = "2026-07-24"
)

// Valid indicates whether the value is a known member of the WorkspaceSnapshotSchemaVersion enum.
func (e WorkspaceSnapshotSchemaVersion) Valid() bool {
	switch e {
	case N20260724:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSnapshotState.
const (
	EMPTY WorkspaceSnapshotState = "EMPTY"
)

// Valid indicates whether the value is a known member of the WorkspaceSnapshotState enum.
func (e WorkspaceSnapshotState) Valid() bool {
	switch e {
	case EMPTY:
		return true
	default:
		return false
	}
}

// AcceptCallingOfferRequest defines model for AcceptCallingOfferRequest.
type AcceptCallingOfferRequest struct {
	SessionId string `json:"sessionId"`
}

// AcceptCallingOfferResult defines model for AcceptCallingOfferResult.
type AcceptCallingOfferResult struct {
	CallId openapi_types.UUID             `json:"callId"`
	State  AcceptCallingOfferResultState  `json:"state"`
	Status AcceptCallingOfferResultStatus `json:"status"`
}

// AcceptCallingOfferResultState defines model for AcceptCallingOfferResult.State.
type AcceptCallingOfferResultState string

// AcceptCallingOfferResultStatus defines model for AcceptCallingOfferResult.Status.
type AcceptCallingOfferResultStatus string

// AccessDiscovery defines model for AccessDiscovery.
type AccessDiscovery struct {
	Actor            Actor            `json:"actor"`
	PlatformOperator bool             `json:"platformOperator"`
	Practices        []PracticeAccess `json:"practices"`
}

// Actor defines model for Actor.
type Actor struct {
	Email   openapi_types.Email `json:"email"`
	Subject string              `json:"subject"`
	Type    ActorType           `json:"type"`
}

// ActorType defines model for Actor.Type.
type ActorType string

// AddLocationRequest defines model for AddLocationRequest.
type AddLocationRequest struct {
	Key              string             `json:"key"`
	Name             string             `json:"name"`
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action           string             `json:"action"`
	ActorSubject     string             `json:"actorSubject"`
	CreatedAt        time.Time          `json:"createdAt"`
	Id               openapi_types.UUID `json:"id"`
	PracticeId       openapi_types.UUID `json:"practiceId"`
	Reason           string             `json:"reason"`
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// Authorization defines model for Authorization.
type Authorization struct {
	ActiveLocation   *Location    `json:"activeLocation,omitempty"`
	Actor            Actor        `json:"actor"`
	Locations        []Location   `json:"locations"`
	Membership       *Membership  `json:"membership,omitempty"`
	PlatformOperator bool         `json:"platformOperator"`
	Practice         Practice     `json:"practice"`
	SupportMode      *SupportMode `json:"supportMode,omitempty"`
}

// CallHistoryItem defines model for CallHistoryItem.
type CallHistoryItem struct {
	AnsweredByEmail string                   `json:"answeredByEmail"`
	Current         bool                     `json:"current"`
	Direction       CallHistoryItemDirection `json:"direction"`
	DurationSeconds int64                    `json:"durationSeconds"`
	EndedAt         *time.Time               `json:"endedAt,omitempty"`
	Id              openapi_types.UUID       `json:"id"`
	LocationId      openapi_types.UUID       `json:"locationId"`
	LocationName    string                   `json:"locationName"`
	Originating     bool                     `json:"originating"`
	Outcome         CallHistoryItemOutcome   `json:"outcome"`
	StartedAt       time.Time                `json:"startedAt"`
	TransferReason  string                   `json:"transferReason"`
	Type            CallHistoryItemType      `json:"type"`
}

// CallHistoryItemDirection defines model for CallHistoryItem.Direction.
type CallHistoryItemDirection string

// CallHistoryItemOutcome defines model for CallHistoryItem.Outcome.
type CallHistoryItemOutcome string

// CallHistoryItemType defines model for CallHistoryItem.Type.
type CallHistoryItemType string

// CallHistoryPage defines model for CallHistoryPage.
type CallHistoryPage struct {
	Items      []CallHistoryItem `json:"items"`
	NextCursor string            `json:"nextCursor"`
}

// CallingCall defines model for CallingCall.
type CallingCall struct {
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	Deadline    time.Time  `json:"deadline"`
	DisplayName string     `json:"displayName"`

	// ExpectedMediaToken Opaque token that identifies the exact WebRTC media leg for the current claim.
	ExpectedMediaToken string `json:"expectedMediaToken"`

	// ExpectedStaffLegId Empty until Telnyx identifies the one staff leg created for this claim.
	ExpectedStaffLegId  string             `json:"expectedStaffLegId"`
	Id                  openapi_types.UUID `json:"id"`
	LocationId          openapi_types.UUID `json:"locationId"`
	LocationName        string             `json:"locationName"`
	NameSource          string             `json:"nameSource"`
	Phone               string             `json:"phone"`
	PhoneSource         string             `json:"phoneSource"`
	PracticeId          openapi_types.UUID `json:"practiceId"`
	ProviderTermination string             `json:"providerTermination"`
	ReasonSource        string             `json:"reasonSource"`
	Recording           *CallingRecording  `json:"recording,omitempty"`
	State               CallingCallState   `json:"state"`
	TransferReason      string             `json:"transferReason"`
	Version             int64              `json:"version"`
}

// CallingCallState defines model for CallingCall.State.
type CallingCallState string

// CallingControlRequest defines model for CallingControlRequest.
type CallingControlRequest struct {
	SessionId string `json:"sessionId"`
}

// CallingDispositionRequest defines model for CallingDispositionRequest.
type CallingDispositionRequest struct {
	Outcome   CallingDispositionRequestOutcome `json:"outcome"`
	SessionId string                           `json:"sessionId"`
}

// CallingDispositionRequestOutcome defines model for CallingDispositionRequest.Outcome.
type CallingDispositionRequestOutcome string

// CallingDispositionResult defines model for CallingDispositionResult.
type CallingDispositionResult struct {
	Call   CallingCall         `json:"call"`
	TaskId *openapi_types.UUID `json:"taskId,omitempty"`
}

// CallingOffer defines model for CallingOffer.
type CallingOffer struct {
	Deadline       time.Time          `json:"deadline"`
	DisplayName    string             `json:"displayName"`
	Id             openapi_types.UUID `json:"id"`
	LocationId     openapi_types.UUID `json:"locationId"`
	LocationName   string             `json:"locationName"`
	NameSource     string             `json:"nameSource"`
	PracticeId     openapi_types.UUID `json:"practiceId"`
	ReasonSource   string             `json:"reasonSource"`
	State          CallingOfferState  `json:"state"`
	TransferReason string             `json:"transferReason"`
	Version        int64              `json:"version"`
}

// CallingOfferState defines model for CallingOffer.State.
type CallingOfferState string

// CallingOfferList defines model for CallingOfferList.
type CallingOfferList struct {
	Items []CallingOffer `json:"items"`
}

// CallingReadinessRequest defines model for CallingReadinessRequest.
type CallingReadinessRequest struct {
	AudioReady      bool   `json:"audioReady"`
	Available       bool   `json:"available"`
	MicrophoneReady bool   `json:"microphoneReady"`
	Registered      bool   `json:"registered"`
	SessionHealthy  bool   `json:"sessionHealthy"`
	SessionId       string `json:"sessionId"`
}

// CallingRecording defines model for CallingRecording.
type CallingRecording struct {
	FailureCode *string               `json:"failureCode,omitempty"`
	State       CallingRecordingState `json:"state"`
}

// CallingRecordingState defines model for CallingRecording.State.
type CallingRecordingState string

// ContactContextInput defines model for ContactContextInput.
type ContactContextInput struct {
	DisplayName    *string `json:"displayName,omitempty"`
	NameSource     *string `json:"nameSource,omitempty"`
	Phone          string  `json:"phone"`
	PhoneSource    *string `json:"phoneSource,omitempty"`
	ReasonSource   *string `json:"reasonSource,omitempty"`
	TransferReason *string `json:"transferReason,omitempty"`
}

// CreateHandoffRequest defines model for CreateHandoffRequest.
type CreateHandoffRequest struct {
	Contact        ContactContextInput `json:"contact"`
	IdempotencyKey string              `json:"idempotencyKey"`
	LocationId     openapi_types.UUID  `json:"locationId"`
	PracticeId     openapi_types.UUID  `json:"practiceId"`
	SourceCallId   string              `json:"sourceCallId"`
}

// CreateStaffTaskRequest defines model for CreateStaffTaskRequest.
type CreateStaffTaskRequest struct {
	CallId             string            `json:"callId"`
	CallerPhone        string            `json:"callerPhone"`
	Category           StaffTaskCategory `json:"category"`
	IdempotencyKey     string            `json:"idempotencyKey"`
	InboundOfficePhone *string           `json:"inboundOfficePhone,omitempty"`
	Message            string            `json:"message"`
	OfficeKey          string            `json:"officeKey"`
	OfficePhone        string            `json:"officePhone"`

	// Patient Compatibility-only fields sent by the existing Abita tool. Acuity may source-label the optional name but never persists the ID or date of birth.
	Patient *StaffTaskPatientCompatibility `json:"patient,omitempty"`
	Source  CreateStaffTaskRequestSource   `json:"source"`
	Summary string                         `json:"summary"`
	Urgency StaffTaskUrgency               `json:"urgency"`
}

// CreateStaffTaskRequestSource defines model for CreateStaffTaskRequest.Source.
type CreateStaffTaskRequestSource string

// EnterSupportModeRequest defines model for EnterSupportModeRequest.
type EnterSupportModeRequest struct {
	DurationMinutes int                `json:"durationMinutes"`
	PracticeId      openapi_types.UUID `json:"practiceId"`
	Reason          string             `json:"reason"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code          string `json:"code"`
		CorrelationId string `json:"correlationId"`
		Message       string `json:"message"`
		Retryable     bool   `json:"retryable"`
	} `json:"error"`
}

// Handoff defines model for Handoff.
type Handoff struct {
	ExpiresAt      time.Time          `json:"expiresAt"`
	Id             openapi_types.UUID `json:"id"`
	SipDestination string             `json:"sipDestination"`
}

// Health defines model for Health.
type Health struct {
	Role   HealthRole   `json:"role"`
	Status HealthStatus `json:"status"`
}

// HealthRole defines model for Health.Role.
type HealthRole string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// InvitationCredentialRequest defines model for InvitationCredentialRequest.
type InvitationCredentialRequest struct {
	Token string `json:"token"`
}

// InvitationPreview defines model for InvitationPreview.
type InvitationPreview struct {
	Email         openapi_types.Email             `json:"email"`
	ExpiresAt     *time.Time                      `json:"expiresAt,omitempty"`
	Kind          InvitationPreviewKind           `json:"kind"`
	LocationScope *InvitationPreviewLocationScope `json:"locationScope,omitempty"`
	Locations     []Location                      `json:"locations"`
	PracticeId    *openapi_types.UUID             `json:"practiceId,omitempty"`
	PracticeName  *string                         `json:"practiceName,omitempty"`
	Role          *InvitationPreviewRole          `json:"role,omitempty"`
}

// InvitationPreviewKind defines model for InvitationPreview.Kind.
type InvitationPreviewKind string

// InvitationPreviewLocationScope defines model for InvitationPreview.LocationScope.
type InvitationPreviewLocationScope string

// InvitationPreviewRole defines model for InvitationPreview.Role.
type InvitationPreviewRole string

// Location defines model for Location.
type Location struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// LocationMutation defines model for LocationMutation.
type LocationMutation struct {
	Audit           AuditEvent `json:"audit"`
	Location        Location   `json:"location"`
	PracticeVersion int64      `json:"practiceVersion"`
}

// MediaToken defines model for MediaToken.
type MediaToken struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// MediaTokenRequest defines model for MediaTokenRequest.
type MediaTokenRequest struct {
	SessionId string `json:"sessionId"`
}

// Membership defines model for Membership.
type Membership struct {
	Id            openapi_types.UUID      `json:"id"`
	LocationScope MembershipLocationScope `json:"locationScope"`
	Role          MembershipRole          `json:"role"`
}

// MembershipLocationScope defines model for Membership.LocationScope.
type MembershipLocationScope string

// MembershipRole defines model for Membership.Role.
type MembershipRole string

// NavigationItem defines model for NavigationItem.
type NavigationItem struct {
	Enabled bool             `json:"enabled"`
	Id      NavigationItemId `json:"id"`
	Label   string           `json:"label"`
}

// NavigationItemId defines model for NavigationItem.Id.
type NavigationItemId string

// OperatorCallingTimeline defines model for OperatorCallingTimeline.
type OperatorCallingTimeline struct {
	CallId     openapi_types.UUID             `json:"callId"`
	Entries    []OperatorCallingTimelineEntry `json:"entries"`
	PracticeId openapi_types.UUID             `json:"practiceId"`
	State      OperatorCallingTimelineState   `json:"state"`
	Version    int64                          `json:"version"`
}

// OperatorCallingTimelineState defines model for OperatorCallingTimeline.State.
type OperatorCallingTimelineState string

// OperatorCallingTimelineEntry defines model for OperatorCallingTimelineEntry.
type OperatorCallingTimelineEntry struct {
	AgeSeconds        int64     `json:"ageSeconds"`
	CommandAction     string    `json:"commandAction"`
	CommandAttempts   int       `json:"commandAttempts"`
	CommandState      string    `json:"commandState"`
	ErrorCode         string    `json:"errorCode"`
	Kind              string    `json:"kind"`
	OccurredAt        time.Time `json:"occurredAt"`
	OpaqueReference   string    `json:"opaqueReference"`
	ReceiptState      string    `json:"receiptState"`
	RecoveryReference *string   `json:"recoveryReference,omitempty"`
}

// Practice defines model for Practice.
type Practice struct {
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`
	Version int64              `json:"version"`
}

// PracticeAccess defines model for PracticeAccess.
type PracticeAccess struct {
	Id         openapi_types.UUID `json:"id"`
	Locations  []Location         `json:"locations"`
	Membership *Membership        `json:"membership,omitempty"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
}

// ProviderReceiptRecovery defines model for ProviderReceiptRecovery.
type ProviderReceiptRecovery struct {
	ReceiptReference string                       `json:"receiptReference"`
	State            ProviderReceiptRecoveryState `json:"state"`
}

// ProviderReceiptRecoveryState defines model for ProviderReceiptRecovery.State.
type ProviderReceiptRecoveryState string

// ProviderReceiptRecoveryRequest defines model for ProviderReceiptRecoveryRequest.
type ProviderReceiptRecoveryRequest struct {
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// RenameTaskRequest defines model for RenameTaskRequest.
type RenameTaskRequest struct {
	ExpectedVersion  int64               `json:"expectedVersion"`
	SupportSessionId *openapi_types.UUID `json:"supportSessionId,omitempty"`
	Title            string              `json:"title"`
}

// SignUpEligibilityRequest defines model for SignUpEligibilityRequest.
type SignUpEligibilityRequest struct {
	Email           openapi_types.Email `json:"email"`
	InvitationToken *string             `json:"invitationToken,omitempty"`
}

// SoftphoneLeaseRequest defines model for SoftphoneLeaseRequest.
type SoftphoneLeaseRequest struct {
	SessionId string `json:"sessionId"`
	Takeover  bool   `json:"takeover"`
}

// SoftphoneState defines model for SoftphoneState.
type SoftphoneState struct {
	// ActiveCallId The User's current durable Call, or empty when capacity is free.
	ActiveCallId   string    `json:"activeCallId"`
	Available      bool      `json:"available"`
	LeaseExpiresAt time.Time `json:"leaseExpiresAt"`
	Owner          bool      `json:"owner"`
	SessionId      string    `json:"sessionId"`
}

// StaffTaskCategory defines model for StaffTaskCategory.
type StaffTaskCategory string

// StaffTaskPatientCompatibility Compatibility-only fields sent by the existing Abita tool. Acuity may source-label the optional name but never persists the ID or date of birth.
type StaffTaskPatientCompatibility struct {
	Dob  *string `json:"dob,omitempty"`
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// StaffTaskReceipt defines model for StaffTaskReceipt.
type StaffTaskReceipt struct {
	Category StaffTaskCategory      `json:"category"`
	Status   StaffTaskReceiptStatus `json:"status"`
	TaskId   openapi_types.UUID     `json:"taskId"`
	Urgency  StaffTaskUrgency       `json:"urgency"`
}

// StaffTaskReceiptStatus defines model for StaffTaskReceipt.Status.
type StaffTaskReceiptStatus string

// StaffTaskUrgency defines model for StaffTaskUrgency.
type StaffTaskUrgency string

// SupportMode defines model for SupportMode.
type SupportMode struct {
	ExpiresAt  time.Time          `json:"expiresAt"`
	Id         openapi_types.UUID `json:"id"`
	PracticeId openapi_types.UUID `json:"practiceId"`
	Reason     string             `json:"reason"`
	StartsAt   time.Time          `json:"startsAt"`
}

// Task defines model for Task.
type Task struct {
	CallId        *openapi_types.UUID `json:"callId,omitempty"`
	CallerName    *string             `json:"callerName,omitempty"`
	Category      *StaffTaskCategory  `json:"category,omitempty"`
	CompletedAt   *time.Time          `json:"completedAt,omitempty"`
	CompletedBy   *TaskActor          `json:"completedBy,omitempty"`
	CreatedAt     time.Time           `json:"createdAt"`
	CreatedBy     TaskActor           `json:"createdBy"`
	Id            openapi_types.UUID  `json:"id"`
	LocationId    openapi_types.UUID  `json:"locationId"`
	LocationName  string              `json:"locationName"`
	Origin        TaskOrigin          `json:"origin"`
	Phone         string              `json:"phone"`
	PracticeId    openapi_types.UUID  `json:"practiceId"`
	SourceCallId  *string             `json:"sourceCallId,omitempty"`
	SourceMessage *string             `json:"sourceMessage,omitempty"`
	State         TaskState           `json:"state"`
	Title         string              `json:"title"`
	UpdatedAt     time.Time           `json:"updatedAt"`
	Urgency       StaffTaskUrgency    `json:"urgency"`
	Version       int64               `json:"version"`
}

// TaskOrigin defines model for Task.Origin.
type TaskOrigin string

// TaskState defines model for Task.State.
type TaskState string

// TaskActor defines model for TaskActor.
type TaskActor struct {
	Email   *openapi_types.Email `json:"email,omitempty"`
	Kind    TaskActorKind        `json:"kind"`
	Subject string               `json:"subject"`
}

// TaskActorKind defines model for TaskActor.Kind.
type TaskActorKind string

// TaskPage defines model for TaskPage.
type TaskPage struct {
	Items      []Task `json:"items"`
	NextCursor string `json:"nextCursor"`
}

// TaskQueryRequest defines model for TaskQueryRequest.
type TaskQueryRequest struct {
	Cursor     *string                   `json:"cursor,omitempty"`
	Limit      *int                      `json:"limit,omitempty"`
	LocationId *openapi_types.UUID       `json:"locationId,omitempty"`
	Ordering   *TaskQueryRequestOrdering `json:"ordering,omitempty"`
	PracticeId openapi_types.UUID        `json:"practiceId"`
	Search     *string                   `json:"search,omitempty"`
}

// TaskQueryRequestOrdering defines model for TaskQueryRequest.Ordering.
type TaskQueryRequestOrdering string

// TaskTransitionRequest defines model for TaskTransitionRequest.
type TaskTransitionRequest struct {
	ExpectedVersion  int64               `json:"expectedVersion"`
	SupportSessionId *openapi_types.UUID `json:"supportSessionId,omitempty"`
}

// WorkspaceSnapshot defines model for WorkspaceSnapshot.
type WorkspaceSnapshot struct {
	Actor            Actor                          `json:"actor"`
	Location         Location                       `json:"location"`
	Membership       *Membership                    `json:"membership,omitempty"`
	Navigation       []NavigationItem               `json:"navigation"`
	PlatformOperator bool                           `json:"platformOperator"`
	Practice         Practice                       `json:"practice"`
	SchemaVersion    WorkspaceSnapshotSchemaVersion `json:"schemaVersion"`
	State            WorkspaceSnapshotState         `json:"state"`
	SupportMode      *SupportMode                   `json:"supportMode,omitempty"`
	Version          int64                          `json:"version"`
}

// WorkspaceSnapshotSchemaVersion defines model for WorkspaceSnapshot.SchemaVersion.
type WorkspaceSnapshotSchemaVersion string

// WorkspaceSnapshotState defines model for WorkspaceSnapshot.State.
type WorkspaceSnapshotState string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// Denied defines model for Denied.
type Denied = ErrorEnvelope

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = ErrorEnvelope

// Unavailable defines model for Unavailable.
type Unavailable = ErrorEnvelope

// GetCallingCallHistoryParams defines parameters for GetCallingCallHistory.
type GetCallingCallHistoryParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	PracticeId openapi_types.UUID `form:"practiceId" json:"practiceId"`
	LocationId openapi_types.UUID `form:"locationId" json:"locationId"`
}

// ReceiveTelnyxWebhookJSONBody defines parameters for ReceiveTelnyxWebhook.
type ReceiveTelnyxWebhookJSONBody map[string]interface{}

// GetTaskCallHistoryParams defines parameters for GetTaskCallHistory.
type GetTaskCallHistoryParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	PracticeId openapi_types.UUID `form:"practiceId" json:"practiceId"`
	LocationId openapi_types.UUID `form:"locationId" json:"locationId"`
}

// InspectSignUpEligibilityJSONRequestBody defines body for InspectSignUpEligibility for application/json ContentType.
type InspectSignUpEligibilityJSONRequestBody = SignUpEligibilityRequest

// RecordCallingDispositionJSONRequestBody defines body for RecordCallingDisposition for application/json ContentType.
type RecordCallingDispositionJSONRequestBody = CallingDispositionRequest

// RequestCallingHangupJSONRequestBody defines body for RequestCallingHangup for application/json ContentType.
type RequestCallingHangupJSONRequestBody = CallingControlRequest

// IssueCallingMediaTokenJSONRequestBody defines body for IssueCallingMediaToken for application/json ContentType.
type IssueCallingMediaTokenJSONRequestBody = MediaTokenRequest

// AcceptCallingOfferJSONRequestBody defines body for AcceptCallingOffer for application/json ContentType.
type AcceptCallingOfferJSONRequestBody = AcceptCallingOfferRequest

// SetCallingReadinessJSONRequestBody defines body for SetCallingReadiness for application/json ContentType.
type SetCallingReadinessJSONRequestBody = CallingReadinessRequest

// AcquireSoftphoneJSONRequestBody defines body for AcquireSoftphone for application/json ContentType.
type AcquireSoftphoneJSONRequestBody = SoftphoneLeaseRequest

// CreateHandoffJSONRequestBody defines body for CreateHandoff for application/json ContentType.
type CreateHandoffJSONRequestBody = CreateHandoffRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationCredentialRequest

// InspectInvitationJSONRequestBody defines body for InspectInvitation for application/json ContentType.
type InspectInvitationJSONRequestBody = InvitationCredentialRequest

// RequeueOperatorProviderReceiptJSONRequestBody defines body for RequeueOperatorProviderReceipt for application/json ContentType.
type RequeueOperatorProviderReceiptJSONRequestBody = ProviderReceiptRecoveryRequest

// AddLocationJSONRequestBody defines body for AddLocation for application/json ContentType.
type AddLocationJSONRequestBody = AddLocationRequest

// ReceiveTelnyxWebhookJSONRequestBody defines body for ReceiveTelnyxWebhook for application/json ContentType.
type ReceiveTelnyxWebhookJSONRequestBody ReceiveTelnyxWebhookJSONBody

// EnterSupportModeJSONRequestBody defines body for EnterSupportMode for application/json ContentType.
type EnterSupportModeJSONRequestBody = EnterSupportModeRequest

// CreateStaffTaskJSONRequestBody defines body for CreateStaffTask for application/json ContentType.
type CreateStaffTaskJSONRequestBody = CreateStaffTaskRequest

// QueryTasksJSONRequestBody defines body for QueryTasks for application/json ContentType.
type QueryTasksJSONRequestBody = TaskQueryRequest

// CompleteTaskJSONRequestBody defines body for CompleteTask for application/json ContentType.
type CompleteTaskJSONRequestBody = TaskTransitionRequest

// ReopenTaskJSONRequestBody defines body for ReopenTask for application/json ContentType.
type ReopenTaskJSONRequestBody = TaskTransitionRequest

// RenameTaskJSONRequestBody defines body for RenameTask for application/json ContentType.
type RenameTaskJSONRequestBody = RenameTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// DiscoverAccess Discover current Practice and Location authorization.
	// (GET /v1/access)
	DiscoverAccess(w http.ResponseWriter, r *http.Request)
	// InspectSignUpEligibility Validate an invitation or provisioned Platform Operator email.
	// (POST /v1/access/sign-up-eligibility)
	InspectSignUpEligibility(w http.ResponseWriter, r *http.Request)
	// GetCallingCall Read the winning User's durable active or disposition Call.
	// (GET /v1/calling/calls/{callId})
	GetCallingCall(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RecordCallingDisposition Resolve the provider-terminated Call and optionally ensure its one follow-up Task.
	// (POST /v1/calling/calls/{callId}/disposition)
	RecordCallingDisposition(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RequestCallingHangup Commit a provider hangup command without claiming termination.
	// (POST /v1/calling/calls/{callId}/hangup)
	RequestCallingHangup(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// GetCallingCallHistory Read authorized exact-phone Call Engagement History for the active Call.
	// (GET /v1/calling/calls/{callId}/history)
	GetCallingCallHistory(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID, params GetCallingCallHistoryParams)
	// IssueCallingMediaToken Issue a short-lived Telnyx JWT to the current softphone owner.
	// (POST /v1/calling/media-token)
	IssueCallingMediaToken(w http.ResponseWriter, r *http.Request)
	// ListCallingOffers List every current offer the User may accept now.
	// (GET /v1/calling/offers)
	ListCallingOffers(w http.ResponseWriter, r *http.Request)
	// AcceptCallingOffer Atomically claim one current offer and commit its Dial command.
	// (POST /v1/calling/offers/{callId}/accept)
	AcceptCallingOffer(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// SetCallingReadiness Commit the media-owning session's current technical readiness.
	// (PUT /v1/calling/readiness)
	SetCallingReadiness(w http.ResponseWriter, r *http.Request)
	// AcquireSoftphone Acquire, renew, or explicitly take over the User's softphone lease.
	// (POST /v1/calling/softphone/lease)
	AcquireSoftphone(w http.ResponseWriter, r *http.Request)
	// GetEvents Stream disposable version hints for one authorized scope.
	// (GET /v1/events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// CreateHandoff Create one authenticated, idempotent Abita handoff.
	// (POST /v1/handoffs)
	CreateHandoff(w http.ResponseWriter, r *http.Request)
	// AcceptInvitation Atomically activate an invitation for the verified identity.
	// (POST /v1/invitations/accept)
	AcceptInvitation(w http.ResponseWriter, r *http.Request)
	// InspectInvitation Inspect only the scope attached to the presented invitation.
	// (POST /v1/invitations/inspect)
	InspectInvitation(w http.ResponseWriter, r *http.Request)
	// GetOperatorCallingTimeline Read one sanitized durable Call timeline as a Platform Operator.
	// (GET /v1/operator/calls/{callId}/timeline)
	GetOperatorCallingTimeline(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RequeueOperatorProviderReceipt Requeue one quarantined provider receipt in Platform Operator Support Mode.
	// (POST /v1/operator/practices/{practiceId}/provider-receipts/{receiptReference}/requeue)
	RequeueOperatorProviderReceipt(w http.ResponseWriter, r *http.Request, practiceId openapi_types.UUID, receiptReference string)
	// AddLocation Add a Location as a Platform Operator in Support Mode.
	// (POST /v1/practices/{practiceId}/locations)
	AddLocation(w http.ResponseWriter, r *http.Request, practiceId openapi_types.UUID)
	// ReceiveTelnyxWebhook Verify and durably receipt one raw Telnyx webhook.
	// (POST /v1/provider/telnyx/webhooks)
	ReceiveTelnyxWebhook(w http.ResponseWriter, r *http.Request)
	// EnterSupportMode Enter time-limited Support Mode for one Practice.
	// (POST /v1/support-mode)
	EnterSupportMode(w http.ResponseWriter, r *http.Request)
	// RevokeSupportMode Revoke the real operator's active Support Mode.
	// (DELETE /v1/support-mode/{supportSessionId})
	RevokeSupportMode(w http.ResponseWriter, r *http.Request, supportSessionId openapi_types.UUID)
	// CreateStaffTask Accept one authenticated current Abita create_staff_task command.
	// (POST /v1/tasks)
	CreateStaffTask(w http.ResponseWriter, r *http.Request)
	// QueryTasks Query the authorized Task rail with protected search input.
	// (POST /v1/tasks/query)
	QueryTasks(w http.ResponseWriter, r *http.Request)
	// ReadTask Read one currently authorized Task.
	// (GET /v1/tasks/{taskId})
	ReadTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// CompleteTask Complete one Task at its last observed version.
	// (POST /v1/tasks/{taskId}/complete)
	CompleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// GetTaskCallHistory Read authorized exact-phone Call Engagement History for one Task.
	// (GET /v1/tasks/{taskId}/history)
	GetTaskCallHistory(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID, params GetTaskCallHistoryParams)
	// ReopenTask Reopen one completed Task at its last observed version.
	// (POST /v1/tasks/{taskId}/reopen)
	ReopenTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// RenameTask Rename one open Task at its last observed version.
	// (PUT /v1/tasks/{taskId}/title)
	RenameTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// GetWorkspace Load the authoritative empty workspace snapshot.
	// (GET /v1/workspace)
	GetWorkspace(w http.ResponseWriter, r *http.Request, params GetWorkspaceParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverAccess operation middleware
func (siw *ServerInterfaceWrapper) DiscoverAccess(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectSignUpEligibility operation middleware
func (siw *ServerInterfaceWrapper) InspectSignUpEligibility(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectSignUpEligibility(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCallingCall operation middleware
func (siw *ServerInterfaceWrapper) GetCallingCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCallingCall(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordCallingDisposition operation middleware
func (siw *ServerInterfaceWrapper) RecordCallingDisposition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordCallingDisposition(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestCallingHangup operation middleware
func (siw *ServerInterfaceWrapper) RequestCallingHangup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestCallingHangup(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCallingCallHistory operation middleware
func (siw *ServerInterfaceWrapper) GetCallingCallHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCallingCallHistoryParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCallingCallHistory(w, r, callId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IssueCallingMediaToken operation middleware
func (siw *ServerInterfaceWrapper) IssueCallingMediaToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IssueCallingMediaToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCallingOffers operation middleware
func (siw *ServerInterfaceWrapper) ListCallingOffers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCallingOffers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptCallingOffer operation middleware
func (siw *ServerInterfaceWrapper) AcceptCallingOffer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptCallingOffer(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCallingReadiness operation middleware
func (siw *ServerInterfaceWrapper) SetCallingReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCallingReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcquireSoftphone operation middleware
func (siw *ServerInterfaceWrapper) AcquireSoftphone(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcquireSoftphone(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Required query parameter "practiceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "practiceId", r.URL.Query(), &params.PracticeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "practiceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "locationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locationId", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locationId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHandoff operation middleware
func (siw *ServerInterfaceWrapper) CreateHandoff(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHandoff(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectInvitation operation middleware
func (siw *ServerInterfaceWrapper) InspectInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperatorCallingTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetOperatorCallingTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperatorCallingTimeline(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequeueOperatorProviderReceipt operation middleware
func (siw *ServerInterfaceWrapper) RequeueOperatorProviderReceipt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "practiceId" -------------
	var practiceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "practiceId", r.PathValue("practiceId"), &practiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		return
	}

	// ------------- Path parameter "receiptReference" -------------
	var receiptReference string

	err = runtime.BindStyledParameterWithOptions("simple", "receiptReference", r.PathValue("receiptReference"), &receiptReference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiptReference", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequeueOperatorProviderReceipt(w, r, practiceId, receiptReference)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddLocation operation middleware
func (siw *ServerInterfaceWrapper) AddLocation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "practiceId" -------------
	var practiceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "practiceId", r.PathValue("practiceId"), &practiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddLocation(w, r, practiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveTelnyxWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveTelnyxWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveTelnyxWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnterSupportMode operation middleware
func (siw *ServerInterfaceWrapper) EnterSupportMode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnterSupportMode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSupportMode operation middleware
func (siw *ServerInterfaceWrapper) RevokeSupportMode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "supportSessionId" -------------
	var supportSessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "supportSessionId", r.PathValue("supportSessionId"), &supportSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "supportSessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSupportMode(w, r, supportSessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateStaffTask operation middleware
func (siw *ServerInterfaceWrapper) CreateStaffTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateStaffTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryTasks operation middleware
func (siw *ServerInterfaceWrapper) QueryTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadTask operation middleware
func (siw *ServerInterfaceWrapper) ReadTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTask operation middleware
func (siw *ServerInterfaceWrapper) CompleteTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskCallHistory operation middleware
func (siw *ServerInterfaceWrapper) GetTaskCallHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTaskCallHistoryParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskCallHistory(w, r, taskId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReopenTask operation middleware
func (siw *ServerInterfaceWrapper) ReopenTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReopenTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameTask operation middleware
func (siw *ServerInterfaceWrapper) RenameTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Required query parameter "practiceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "practiceId", r.URL.Query(), &params.PracticeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "practiceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "locationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locationId", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locationId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.GetReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/access/sign-up-eligibility", wrapper.InspectSignUpEligibility)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/access", wrapper.DiscoverAccess)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/invitations/inspect", wrapper.InspectInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/invitations/accept", wrapper.AcceptInvitation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspace", wrapper.GetWorkspace)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/support-mode", wrapper.EnterSupportMode)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/support-mode/{supportSessionId}", wrapper.RevokeSupportMode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/practices/{practiceId}/locations", wrapper.AddLocation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.GetEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/handoffs", wrapper.CreateHandoff)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/provider/telnyx/webhooks", wrapper.ReceiveTelnyxWebhook)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/softphone/lease", wrapper.AcquireSoftphone)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/calling/readiness", wrapper.SetCallingReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/media-token", wrapper.IssueCallingMediaToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/offers", wrapper.ListCallingOffers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/offers/{callId}/accept", wrapper.AcceptCallingOffer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/calls/{callId}", wrapper.GetCallingCall)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/calls/{callId}/hangup", wrapper.RequestCallingHangup)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/calls/{callId}/disposition", wrapper.RecordCallingDisposition)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/calls/{callId}/history", wrapper.GetCallingCallHistory)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks", wrapper.CreateStaffTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks/query", wrapper.QueryTasks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tasks/{taskId}", wrapper.ReadTask)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/tasks/{taskId}/title", wrapper.RenameTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks/{taskId}/complete", wrapper.CompleteTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks/{taskId}/reopen", wrapper.ReopenTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tasks/{taskId}/history", wrapper.GetTaskCallHistory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/operator/calls/{callId}/timeline", wrapper.GetOperatorCallingTimeline)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/operator/practices/{practiceId}/provider-receipts/{receiptReference}/requeue", wrapper.RequeueOperatorProviderReceipt)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D1pcyI5sn9FUW8j9sMD4z5mJsbfaExPs4ttxtDdb1+Pn0OuSkDrQqqRVLhZh//7Cx11q4DCQB/Tn3yU",
	"SkrlrcxU1qPns0XEKFApvLNHj4OIGBWg/3iDg2v4MwYh1V8+oxKo/hVHUUh8LAmjnX8LRtX/hD+HBVa/",
	"/Y3D1Dvz/quTTd0xT0WnzznjfbqEkEXgPT09tbwAhM9JpCbzzrwBXeKQBIibhU+8p5bXY3QaEv+IUEzm",
	"kEAAAZIcU0HUI0QEogyFjM6AI7zEJMR3IWgoz4ESCI4HYy/mHKhEJAAqiVyhEPv3AskC6DiWc8aJXGkQ",
	"31P1txruY3lMWC+IEITOEOOIWAL7HDTgOExAS7B5PLC6GlOEQ4ACiIAGQP2VorGERcQ45iRcoZjm6fzU",
	"sotrCen6PkSyh8OQ0NnVdAo8JzA4CDTT4HDEWQRcEiVWUxwKaHlR7l+PngAhCKMDTZIF/jwEOpNz7+zl",
	"6WnLWxCa/P2i5clVBN6ZJyQndKbhSfbgnX3KTXSTDmV3/wZfKiS7wBVx2BRaH4ehAXXK+AJL78yLYxJ4",
	"FeBanpBYaoICjRcKwKu3b/vXg8vfvJbXu7q87PcmhT/6517Lu+73ri57g6F58v6yezn+2L/Wjy77/fPx",
	"7flgPLoaDyaDq0s9fHw1/KAfv70aDq8+3r4f3V73f38/UO/c1EAVizxY3V6vPzKrd4fX/e75v257w+7g",
	"Qv+n/z+jgVl+cNkfDn4bvBn2HfOWSWEWaSXoSpBRRxghzonw2RL4qiE9sC8Z3yQMXT3oqeVFIZaKblcR",
	"cGxftADdMRYCpnoUx74kvlmASFiITQuM7BtmL2oOOyvmHK8q6DFAO8DJr+3GlQW6AYZggUlYYFjzHxdv",
	"xGalDCvZM/OPjGvevb/oKg4cDbuTt1fXF7dXo/51d3J1vQV32GVaRUicGw6CITMKcDftcg+rkl55sVGv",
	"tDyKF9BYHSn8RRHjcpzXaBvURAU1pRlaegcWIieG4oDI/jIxGI0khxiLUtmH5s/xGmbwOSgj2pWFHQZY",
	"QluSBbh4i2ynNBP+31LHcsCiZhPPJ4YeUsBFAb6Wi1oWqylkeVy5yaedlP/ghBgNKbiERD426ah0XELg",
	"rbVmaN/cXh/m1ypqwpa3gMUdcDEn0aZZLrKRjXX3tho7xykXLNj42jg3tFarJ1PnMeeA38UOyj95R4Rk",
	"fDWQsGjKEFQ8AIfgzaqfKP2q6BrX2Y29gHBI1UKi6QeXb67eX7q9iSDmeoNj8BkNREHGCJU/v/a00iQL",
	"NdVpOgGhEmagmUt5nodQJAnqB82GX1rNXxnAOJkRiqX604k7FkufLb5Kh4831NX60Kc95FrtWnYHet3h",
	"cLPlz3Cf57U8jFWWKpCyRKhWheUrwGeEyXi/SM0NcjjCM2goh6mO3EpZlmXeoTMpfJa9mIuC1qvDsV6z",
	"8E7dDgmdqR9Nj0CMUvAbslQAOAgJhQZvEBGFeFUrkPA50lBcQEDwhN2DZtTiIfcqwn/GgKR6iuQcJxGD",
	"KQETLYDP2JfoI9xdT3pooWZCIczQlHH92DIM8kNMFicuKBMoxhJPp0OYGXVThKK/iKQ6S0sSogmEdPW5",
	"DAajgISaQa9uPQYLBRFrlv9CylB5o2MWc9/9OJozuubJujebuX8RZ0sSAJ8AX2hxrtFWxhlbsy4Hn/HA",
	"6vZNwkro7Dod7zrofzllv4XmXgIXFk/1pvpF1VS7VHnBG16npg2KcmogYZIiSxSlvsBnDsVeoKpTFJ1a",
	"ws02GWLWaUtGJWfhVx3osqCeExExE7ndDVyHP7OD81HY8057zAz4trvdMay3pehri6lEDYv7XU6Veqk1",
	"W9GxyYbg79+6fqWGZZfowJr56kO035JyfYbOzOnjREVvoQY1iw5JY5XS3C9O5WFTSNXMuAbma8ABoSDE",
	"btoQxwFhao6V+/RXyOBUHy+Iz5m2dGvm4DAjQgI32anqc6sT3wEO5Xy1dsw+jUwBsOpWWnncVIDMY2Yt",
	"dXL+VwOyTDEJYw49G7rZLOCDy0n/8jx1xq7PjSum0x7KrHUHQ6cpcyQ4ajbEqMS+VD/gsxzQKG7KaiXV",
	"XCbiBp1ZjnTXO+cRlhK4OqD83x9//PenF+1fbz6dtn+9efyl9eL109+81kb3feNaZQW88YWqis298pPj",
	"lRJdzOacdNGHqneYBmw63U0H+Ia0G/WWgwO0RYVFxCRQf/XPSlJim+xCQ1vb0FYKTaRemt58ju6ot1yF",
	"VSo4aaUorqeg9u4nWNzvSEPnBn/6aSP21YvAR88QHh9LmDGT4VwbY0522Ete2IF7cvB96rb/F7f/o6DL",
	"fj25PWvfPJ62Xvz6qxtaQu9YTIOr6ZT48JxtL0AIG0IroHwLjmd68X/ulMJjzwY8wpLYSPlW5BqZ8T22",
	"UG/ekZDIVSZZeSOEZ2pe53kpXiwwr9D39eb9xnymmGNraN/b8a7jiZbNPMPnmNchtAmF8wQrEiBFQrbD",
	"DGKXrPepBJ5Ltuwm7Eko+YLQWJp/LfBn44QnOK11yZ+RiyzbrJ11Z5pELO/EibNCyU/DIgH1bmNzWON0",
	"+YxzCHO2ap1OcKBR8lWdJ11mVgVCngGLS+cnq2KsNJdBgQux1mloitLPEeEgDpDaEiQ6ByHrA56u02Tp",
	"pVYOPueetf/ecMuchQU9p6QXh20ckVzQrU3ojIMQhr1DjYvtCpXYfYPKIw2La2cDuiRSI6GXluHtpl5k",
	"knQo2LWfC/L+6uUmiM0s6yEdcVgSeDhc5c8OzHpPaJCnzui625sMev3bweWHwaRrQ9jblAdlPuLYZ8W0",
	"Ync49FreuD80EfR17+6nOqFxAsIMrw1olUWie34xUHgZT7pv325mZ43krE4q26uLX/KVIE2iMtttlbq3",
	"6NI1tcVKCYQXsdyp4CUOyEZ/LFcQleOOJjyREPXDmmDehgBeumx1tpbdhgs/xVzmYY1Nqr22UU+bzEUG",
	"+FedG7ko1B7tX0aeo8eeqSk0QHqOMhguRFziJZkZN6l5mRFQ5VHVBClJwShILO6TOuC2D8qr93LZVqED",
	"hlLqX53KHd9BuKXWMWNbKXiufSfFVzbsOCELSPImhykCByo5aVBJXANgn0oTB3imvfo6a9L3lDVJj67F",
	"Is1SXiOjSQMGMfhvaK1msHtZnM8WC0yDbn2RbjJCSlhE5gbTVlOOExao8qo6AdWG0hN/rxpp8XWZTKNy",
	"IKYLc65hChxofU0GkEjWw6vUyBL4qjCNM/B12755fP3KFeZx+1tl8PK4KdOmhNgqYUo7aeUZo4A9Fz+O",
	"cvWsR/Pp9pvHpCYvuS6vWLo/ofYahldT7+zT1lW8jdDzNVQ013iMLrV0o1Fkjs/XhpeuYafrMjx5e3eJ",
	"cRiRUf/y3J00L22ysvy6i0E1O97Rwdz/1QwXzNeguH339ERSrvRhR/nb6dpDy5NEhvDcyGUZ9mRaF57G",
	"ZEbfR/2QzGygfEd01UY4cht59fLUmd9IgiuTvYRxzMLOvbKp1HnJIWABxz4ftTyJ70FJzhbx1HzSP31t",
	"7Z5S69z43kqWaqzeP34vgP9dpOW3QcyVS4/UKy3EOAJdUfswB4p8HGGfSH11dcoBnGWyG6ozQkWYfvMj",
	"NHugwLeow9i+0qIESbJEfgetIv6c1KlkEHPK+o5oz1bNE0WMULnQF+BbXsD8WP2eBC5YJImPtTBBQNJ4",
	"BlfKm+NQOy9yXmCQDDXrs2Kb+KV02zv/bpvRcIWmBMJAIKG4425lS7mJUAdJ1L0jEiPJWHiCun6seGOB",
	"V8hkoNr6lGiKriOzPlIqG93FElFYAkeR0l9CmsrswbniN8UFiE3RHeFyfvKHrSHNZ5rYXUkyf35dG+Av",
	"Z563vn5Y5aN60lur2fhk+4wcdTVibyvZdQLL3GR3x/q3rqXcX54zTRTYtQspznWpycrMuf3OyWx+G3Gi",
	"2w4o11ftJtS/0Fs9qTvtOy7eQPsqskx7vIkpMZcNQNxYDJmmRdOZN8UnFb0OF+QxqfLaHMCzhEqNC6Hh",
	"bZv0pTcbF1XrpTc9d7jXa19puNAXvcRXucZ+2+sOh7dpsMpred03g0n3tjtwSuua6y3Pq7mqGXCxJlte",
	"DeiN+pc6fncxGvbrYs2pv19Vr1HQlAN21shfqFw6uXhikJAFCC1zZBvKM3deNvKxxAxfdWrnwD0bymnY",
	"pC/DuH/9YdDr11QZ1V3td4fDkvF1Wzz4FUmtvo9zL1It9Xu8c5zBr4Om5YVkYbKXaQ3STxtLkBoqQMYD",
	"4LaKOk3BGLFNvZKbPdSKAub+fIfq3GyZOtRP0n5T31AAZUMgxLXXj4zfiwj7MKY4EnMmD9r3Zpcs+K59",
	"GmiaWtxavEvZSFea63DNH/T/cuySyM3L05c/t09/ab98XVueVDC8/YvR5F816na3/hJ7s4/FPebNV2L7",
	"1vSu8Aok3aqPhVYRfqzUzVgtbVj2DjAH3o1NWZn5622yq398nHiWGJqo+mkmaXMpI6N5+JL48MY8rk5j",
	"EjdtO6ydFC9smPdJxwOnrBqMsvGDkS5kQyY90ULv4gWmNkPYQpgGSIkzUujnU+yDQA9EztGICTnjMP59",
	"mPWia6XBLJsmEvp9GxgXZrZA32bUo5ISOTQnVAoTerDeWxm40SBH2rOMf38xCTegOCLemffq5PTklafL",
	"m+eaLp25rvXrhGSp+XMGWhkxTV+rAr3fQA7JEmhSuJdrlfjy9HRvbets2aGjX92IM4V8RATiMaWEzk4K",
	"jOadfbpRfye74ck9q7rtpBfCvsx+rpPuezymmsBpFz4CAmGuSR+Y3oU/nb6qWyiFvJPvIuhEzPJFB6f5",
	"NSdWkiZsNg13QLyUm76t6fFohmYShKacLXKypTH0+vTFVhgqtIDU722BWdvdcmdCJDX9KX7TwHZiiLTU",
	"J8Y32arpCWW4PCNeR5AZbcdRG7Lkic7iMeGg6IAK5YtU0i2eMRAg5BtmxGQvZK1N6zwVTZLkMTwdkL2q",
	"lbM1jU6XwMmUQNDW5ytkcauUjEGv7W96FDbJyWueaT7gkOj4M6YoS1ohxpGuqFbaHgI0slYZJWYZ6R1l",
	"3OMbc6V/is6jiW49rVOQ+fvuylxwvAAJXOisPFEYVCYkSfCfZeU3RTq3cjTb5EffHJAnCtf3Hf1QrdBB",
	"oNNM6CFx0L8h/aJMms5aPBBtIZM8WuJymMSRTmhk/RL0djfxSSf3Qr22Mbd4qy0Zjso++9dq9R01jqzW",
	"aptdOPj53NJcmh4noeFq20pD25s0/xUSeg8BUsdvy+ynm7kw1yD7ePLx+vTXzcPTltn7ECjBwiVomUrv",
	"r1iMykRT5HEZrhBQEXNARArd1mnKwpA9KKNi8btezuaYzuJonYhpnFtOeGdGfxfiVeqts5VovTyWdTCI",
	"1ic8KvXRjUgJwcl3zPs9vUmEU8ZHhjeTg6s+47LYNkdT1kZm7ZQ287lpeLel/2Hb4x2L0Vt24j9j4Kvc",
	"zCa2m5/p2A5Mviehg00v4QGERBGeKX0FAqjSUoQif84ZZSGbER+HSIeJv3JVvw9XCGc+nW7019apH6O1",
	"+3SGZ7BQ4myRmnb9s26S2y/STQLb6eWZmmOXEDFY/i10HjuE/qzevTmyW5LboYMnx3PGZTskSwjQHWcP",
	"ArjttFj6DMIPtyNhXs0+CCORQ51tHPmPjxMkWaE5pUhq8ZAuFquyLJtOtb6sUbVDIgrfRTho4KfSQcrB",
	"MX3MQwJCtpPuVO0p4UKmISBsTjEa1m/odKa2i2AJfJWSTu9BE/O9Fgu8Qlh/pwJR9lBHyMyImrH1aqj6",
	"zYtv3FWs/+bIkVVe7ddEXIHMxFu0tMXU12dw+KxWJxKFTH8ghusZvm+z3JVsoVyQcGXcRn1EKkqDci2N",
	"g63PUOcEh4nLWZUIngbxlRDEDhkYp45kMeB/sHNMpdHckVmzVJq9JrIeANemJUUYDpFOCH7fPGgPNkrr",
	"GmeOPehgma3DztWdS/DnVHvMKZ9VWTA1vx1dvL1OG2sWSOlzqBi887rBV8uEJe9FzEn0natAwwYtxIHC",
	"QytvCcIVkvgekM4RyeweRIYjzWIZD8Iy+Xhd3SG6v7TV/S6zXzrflmps93x6LpTkHTJFIOGzNJhpC8kB",
	"L4psW56wwplvWEwDCFBlnhM0oEQae6Rb4OtkHQ2sU8fB/jv5shrCtOSzpkkFxGEK0td3Cb4Zzh1rLOSr",
	"E2y1gSlO0OdnxaS5Y7fwWZTj17nppCTqlWShTeOhDLWrFeRWCvLF/goD7A4d/Gc/WqB8whDasQA0HoyQ",
	"Rd2Pk3IxVfpYLgn6dPNUSJ8aYqd8mW6uhdI+dtJeGcpQbNk1S7eKLc9aWeL5QLy7rnvVsc9AhU9Xub58",
	"mdYFai3pUAvfbQQnd87R0cRq/j4JNiYVCOm3TN3sR0whx8ZKj78SA25V5TECGijvPkPmF6/osKRC+iaj",
	"4gEtDghLif25cjyYTThmAfwc7JY5mK3zKCdWZK6lTZ1TWNcF5zuo8qjbmiswjZU3p9RRmuHSaS3G76ch",
	"e0A2RfWt1X/obwmlW8tfnUYJbyAsEK6WDDmYK/0caecxOx08ddJceFK32nkst3Z46mjtE8OGXHYMyfKl",
	"fg9bceOejyzFyR3dKuqXaNp35kAR0g1NM46soeualtRU49mb15DWQ6MHLHJ+Qwvp1nn6F2q/kx6nWfgf",
	"2aNEC2i0aEXwZ4w5ppLQvJZLkEuoo2zQ3kBAFyzIHdxq9EChj06NX5x9wfeYEn2oBET1e8RHPjhWWmiu",
	"zTikNcULO9x64gH53hMNQYBwrqTaafCUBNTxu5GVjtRp184D3M0Zuxdrax+BLMGkaT+a4c9wwd1XwYwU",
	"lG/bbMF/r6tXW6xOth7CKitqQozbTJX2H2zfhl3ZZb+10OqwtDJ3ZCzYiTJT2o7jhyRPbgmWUdRewmov",
	"7C0sNxXLfecPdIiqa29/ZF1S/JpxtSTa1MGUJOQ7VhqaLNpLbuvLuhAUNp8GOJNrG27u6jyWr5A+GekL",
	"wdwYLCuOJbuHIs9tNpOOT4/v80Dm0BcFTHANdPBNnY0UxPpgzQGHKDni/F0k9V5uS2A62G6IV6e9DQ4a",
	"sa58+ubYSb1ybyHnoXqqEByFeIXYVGdAQn2RLWdf0kLzveqyLYBTj7XxMH01ciDhNF734zDRMMBuAt/V",
	"AHuaRTfBddM+41Z/5fhWCVW1qEOLWsekDWsFTvdmmNi20oeQtUoDiCNLWdpQw5kaAmqL4TQvc0xCXe37",
	"fdtlTQ5TmpvlEDIE6MvWEWdSd11ApjsFIjSKZZm5Hk23r/p7b9eAA6vINxvhtHXY1xkLNV1T6ksvNAbz",
	"BT/fVIzTqpdwVWaKOpp3kq5Ya6y5HXF0DjiMGqs2U/kCuqwmQGH6k6mzZpaHDbPK2B+X0Vx1axppmvuN",
	"K2NKJEMsJGJ3yk5DkNRk1ErBFjdvTA+6Ztdu9iAJP67d/GWv3SQsXcu1HFgEa68eq+c/9PZh9bbB8g+1",
	"3UwkFM6My5Kavd3Vd9q60VntnvWf/8bFoNpI/6sRAQXYj9vyTk7XnbR1Lbdi+QZMnhbGrnNL0p55f6ly",
	"5t1ZuNpjcH3fk6w6WdgXvqXbdcz2PilWXNsvBbh2Vgl05RvU2SiXYlfLYqX2GhCFbLXQxeGxohAE6N1k",
	"MhqjXBvZ0HaYE2edDo7ICdYN207gM1Z2wHu6efr/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
