//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AcceptCallingOfferResultState.
const (
	AcceptCallingOfferResultStateCONNECTED        AcceptCallingOfferResultState = "CONNECTED"
	AcceptCallingOfferResultStateCONNECTING       AcceptCallingOfferResultState = "CONNECTING"
	AcceptCallingOfferResultStateFOLLOWUPREQUIRED AcceptCallingOfferResultState = "FOLLOW_UP_REQUIRED"
	AcceptCallingOfferResultStateNEEDSDISPOSITION AcceptCallingOfferResultState = "NEEDS_DISPOSITION"
	AcceptCallingOfferResultStateOFFERING         AcceptCallingOfferResultState = "OFFERING"
	AcceptCallingOfferResultStateRECONCILING      AcceptCallingOfferResultState = "RECONCILING"
	AcceptCallingOfferResultStateRESOLVED         AcceptCallingOfferResultState = "RESOLVED"
	AcceptCallingOfferResultStateUNANSWERED       AcceptCallingOfferResultState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the AcceptCallingOfferResultState enum.
func (e AcceptCallingOfferResultState) Valid() bool {
	switch e {
	case AcceptCallingOfferResultStateCONNECTED:
		return true
	case AcceptCallingOfferResultStateCONNECTING:
		return true
	case AcceptCallingOfferResultStateFOLLOWUPREQUIRED:
		return true
	case AcceptCallingOfferResultStateNEEDSDISPOSITION:
		return true
	case AcceptCallingOfferResultStateOFFERING:
		return true
	case AcceptCallingOfferResultStateRECONCILING:
		return true
	case AcceptCallingOfferResultStateRESOLVED:
		return true
	case AcceptCallingOfferResultStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for AcceptCallingOfferResultStatus.
const (
	ACCEPTED       AcceptCallingOfferResultStatus = "ACCEPTED"
	ALREADYCLAIMED AcceptCallingOfferResultStatus = "ALREADY_CLAIMED"
	EXPIRED        AcceptCallingOfferResultStatus = "EXPIRED"
	INELIGIBLE     AcceptCallingOfferResultStatus = "INELIGIBLE"
)

// Valid indicates whether the value is a known member of the AcceptCallingOfferResultStatus enum.
func (e AcceptCallingOfferResultStatus) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case ALREADYCLAIMED:
		return true
	case EXPIRED:
		return true
	case INELIGIBLE:
		return true
	default:
		return false
	}
}

// Defines values for ActorType.
const (
	ActorTypeHUMAN            ActorType = "HUMAN"
	ActorTypePLATFORMOPERATOR ActorType = "PLATFORM_OPERATOR"
)

// Valid indicates whether the value is a known member of the ActorType enum.
func (e ActorType) Valid() bool {
	switch e {
	case ActorTypeHUMAN:
		return true
	case ActorTypePLATFORMOPERATOR:
		return true
	default:
		return false
	}
}

// Defines values for CallHistoryItemDirection.
const (
	INBOUND CallHistoryItemDirection = "INBOUND"
)

// Valid indicates whether the value is a known member of the CallHistoryItemDirection enum.
func (e CallHistoryItemDirection) Valid() bool {
	switch e {
	case INBOUND:
		return true
	default:
		return false
	}
}

// Defines values for CallHistoryItemOutcome.
const (
	CallHistoryItemOutcomeCONNECTED        CallHistoryItemOutcome = "CONNECTED"
	CallHistoryItemOutcomeCONNECTING       CallHistoryItemOutcome = "CONNECTING"
	CallHistoryItemOutcomeFOLLOWUPREQUIRED CallHistoryItemOutcome = "FOLLOW_UP_REQUIRED"
	CallHistoryItemOutcomeNEEDSDISPOSITION CallHistoryItemOutcome = "NEEDS_DISPOSITION"
	CallHistoryItemOutcomeOFFERING         CallHistoryItemOutcome = "OFFERING"
	CallHistoryItemOutcomeRECONCILING      CallHistoryItemOutcome = "RECONCILING"
	CallHistoryItemOutcomeRESOLVED         CallHistoryItemOutcome = "RESOLVED"
	CallHistoryItemOutcomeUNANSWERED       CallHistoryItemOutcome = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the CallHistoryItemOutcome enum.
func (e CallHistoryItemOutcome) Valid() bool {
	switch e {
	case CallHistoryItemOutcomeCONNECTED:
		return true
	case CallHistoryItemOutcomeCONNECTING:
		return true
	case CallHistoryItemOutcomeFOLLOWUPREQUIRED:
		return true
	case CallHistoryItemOutcomeNEEDSDISPOSITION:
		return true
	case CallHistoryItemOutcomeOFFERING:
		return true
	case CallHistoryItemOutcomeRECONCILING:
		return true
	case CallHistoryItemOutcomeRESOLVED:
		return true
	case CallHistoryItemOutcomeUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for CallHistoryItemType.
const (
	CALL CallHistoryItemType = "CALL"
)

// Valid indicates whether the value is a known member of the CallHistoryItemType enum.
func (e CallHistoryItemType) Valid() bool {
	switch e {
	case CALL:
		return true
	default:
		return false
	}
}

// Defines values for CallingCallState.
const (
	CallingCallStateCONNECTED        CallingCallState = "CONNECTED"
	CallingCallStateCONNECTING       CallingCallState = "CONNECTING"
	CallingCallStateFOLLOWUPREQUIRED CallingCallState = "FOLLOW_UP_REQUIRED"
	CallingCallStateNEEDSDISPOSITION CallingCallState = "NEEDS_DISPOSITION"
	CallingCallStateRECONCILING      CallingCallState = "RECONCILING"
	CallingCallStateRESOLVED         CallingCallState = "RESOLVED"
	CallingCallStateUNANSWERED       CallingCallState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the CallingCallState enum.
func (e CallingCallState) Valid() bool {
	switch e {
	case CallingCallStateCONNECTED:
		return true
	case CallingCallStateCONNECTING:
		return true
	case CallingCallStateFOLLOWUPREQUIRED:
		return true
	case CallingCallStateNEEDSDISPOSITION:
		return true
	case CallingCallStateRECONCILING:
		return true
	case CallingCallStateRESOLVED:
		return true
	case CallingCallStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for CallingDispositionRequestOutcome.
const (
	CallingDispositionRequestOutcomeFOLLOWUPREQUIRED CallingDispositionRequestOutcome = "FOLLOW_UP_REQUIRED"
	CallingDispositionRequestOutcomeRESOLVED         CallingDispositionRequestOutcome = "RESOLVED"
)

// Valid indicates whether the value is a known member of the CallingDispositionRequestOutcome enum.
func (e CallingDispositionRequestOutcome) Valid() bool {
	switch e {
	case CallingDispositionRequestOutcomeFOLLOWUPREQUIRED:
		return true
	case CallingDispositionRequestOutcomeRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for CallingOfferState.
const (
	CallingOfferStateOFFERING CallingOfferState = "OFFERING"
)

// Valid indicates whether the value is a known member of the CallingOfferState enum.
func (e CallingOfferState) Valid() bool {
	switch e {
	case CallingOfferStateOFFERING:
		return true
	default:
		return false
	}
}

// Defines values for CallingRecordingState.
const (
	FAILED    CallingRecordingState = "FAILED"
	INTENDED  CallingRecordingState = "INTENDED"
	READY     CallingRecordingState = "READY"
	RECORDING CallingRecordingState = "RECORDING"
)

// Valid indicates whether the value is a known member of the CallingRecordingState enum.
func (e CallingRecordingState) Valid() bool {
	switch e {
	case FAILED:
		return true
	case INTENDED:
		return true
	case READY:
		return true
	case RECORDING:
		return true
	default:
		return false
	}
}

// Defines values for HealthRole.
const (
	PortalApi       HealthRole = "portal-api"
	ProviderIngress HealthRole = "provider-ingress"
	Realtime        HealthRole = "realtime"
)

// Valid indicates whether the value is a known member of the HealthRole enum.
func (e HealthRole) Valid() bool {
	switch e {
	case PortalApi:
		return true
	case ProviderIngress:
		return true
	case Realtime:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewKind.
const (
	InvitationPreviewKindPLATFORMOPERATOR   InvitationPreviewKind = "PLATFORM_OPERATOR"
	InvitationPreviewKindPRACTICEINVITATION InvitationPreviewKind = "PRACTICE_INVITATION"
)

// Valid indicates whether the value is a known member of the InvitationPreviewKind enum.
func (e InvitationPreviewKind) Valid() bool {
	switch e {
	case InvitationPreviewKindPLATFORMOPERATOR:
		return true
	case InvitationPreviewKindPRACTICEINVITATION:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewLocationScope.
const (
	InvitationPreviewLocationScopeALL      InvitationPreviewLocationScope = "ALL"
	InvitationPreviewLocationScopeSELECTED InvitationPreviewLocationScope = "SELECTED"
)

// Valid indicates whether the value is a known member of the InvitationPreviewLocationScope enum.
func (e InvitationPreviewLocationScope) Valid() bool {
	switch e {
	case InvitationPreviewLocationScopeALL:
		return true
	case InvitationPreviewLocationScopeSELECTED:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewRole.
const (
	InvitationPreviewRoleADMIN InvitationPreviewRole = "ADMIN"
	InvitationPreviewRoleSTAFF InvitationPreviewRole = "STAFF"
)

// Valid indicates whether the value is a known member of the InvitationPreviewRole enum.
func (e InvitationPreviewRole) Valid() bool {
	switch e {
	case InvitationPreviewRoleADMIN:
		return true
	case InvitationPreviewRoleSTAFF:
		return true
	default:
		return false
	}
}

// Defines values for MembershipLocationScope.
const (
	MembershipLocationScopeALL      MembershipLocationScope = "ALL"
	MembershipLocationScopeSELECTED MembershipLocationScope = "SELECTED"
)

// Valid indicates whether the value is a known member of the MembershipLocationScope enum.
func (e MembershipLocationScope) Valid() bool {
	switch e {
	case MembershipLocationScopeALL:
		return true
	case MembershipLocationScopeSELECTED:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRole.
const (
	MembershipRoleADMIN MembershipRole = "ADMIN"
	MembershipRoleSTAFF MembershipRole = "STAFF"
)

// Valid indicates whether the value is a known member of the MembershipRole enum.
func (e MembershipRole) Valid() bool {
	switch e {
	case MembershipRoleADMIN:
		return true
	case MembershipRoleSTAFF:
		return true
	default:
		return false
	}
}

// Defines values for NavigationItemId.
const (
	CallCenter NavigationItemId = "call-center"
	Recordings NavigationItemId = "recordings"
	Settings   NavigationItemId = "settings"
	Tasks      NavigationItemId = "tasks"
)

// Valid indicates whether the value is a known member of the NavigationItemId enum.
func (e NavigationItemId) Valid() bool {
	switch e {
	case CallCenter:
		return true
	case Recordings:
		return true
	case Settings:
		return true
	case Tasks:
		return true
	default:
		return false
	}
}

// Defines values for OperatorCallingTimelineState.
const (
	OperatorCallingTimelineStateCONNECTED        OperatorCallingTimelineState = "CONNECTED"
	OperatorCallingTimelineStateCONNECTING       OperatorCallingTimelineState = "CONNECTING"
	OperatorCallingTimelineStateFOLLOWUPREQUIRED OperatorCallingTimelineState = "FOLLOW_UP_REQUIRED"
	OperatorCallingTimelineStateNEEDSDISPOSITION OperatorCallingTimelineState = "NEEDS_DISPOSITION"
	OperatorCallingTimelineStateOFFERING         OperatorCallingTimelineState = "OFFERING"
	OperatorCallingTimelineStateRECONCILING      OperatorCallingTimelineState = "RECONCILING"
	OperatorCallingTimelineStateRESOLVED         OperatorCallingTimelineState = "RESOLVED"
	OperatorCallingTimelineStateUNANSWERED       OperatorCallingTimelineState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the OperatorCallingTimelineState enum.
func (e OperatorCallingTimelineState) Valid() bool {
	switch e {
	case OperatorCallingTimelineStateCONNECTED:
		return true
	case OperatorCallingTimelineStateCONNECTING:
		return true
	case OperatorCallingTimelineStateFOLLOWUPREQUIRED:
		return true
	case OperatorCallingTimelineStateNEEDSDISPOSITION:
		return true
	case OperatorCallingTimelineStateOFFERING:
		return true
	case OperatorCallingTimelineStateRECONCILING:
		return true
	case OperatorCallingTimelineStateRESOLVED:
		return true
	case OperatorCallingTimelineStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for TaskState.
const (
	COMPLETED TaskState = "COMPLETED"
	OPEN      TaskState = "OPEN"
)

// Valid indicates whether the value is a known member of the TaskState enum.
func (e TaskState) Valid() bool {
	switch e {
	case COMPLETED:
		return true
	case OPEN:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSnapshotSchemaVersion.
const (
	N20260724 WorkspaceSnapshotSchemaVersion = "2026-07-24"
)

// Valid indicates whether the value is a known member of the WorkspaceSnapshotSchemaVersion enum.
func (e WorkspaceSnapshotSchemaVersion) Valid() bool {
	switch e {
	case N20260724:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSnapshotState.
const (
	EMPTY WorkspaceSnapshotState = "EMPTY"
)

// Valid indicates whether the value is a known member of the WorkspaceSnapshotState enum.
func (e WorkspaceSnapshotState) Valid() bool {
	switch e {
	case EMPTY:
		return true
	default:
		return false
	}
}

// AcceptCallingOfferRequest defines model for AcceptCallingOfferRequest.
type AcceptCallingOfferRequest struct {
	SessionId string `json:"sessionId"`
}

// AcceptCallingOfferResult defines model for AcceptCallingOfferResult.
type AcceptCallingOfferResult struct {
	CallId openapi_types.UUID             `json:"callId"`
	State  AcceptCallingOfferResultState  `json:"state"`
	Status AcceptCallingOfferResultStatus `json:"status"`
}

// AcceptCallingOfferResultState defines model for AcceptCallingOfferResult.State.
type AcceptCallingOfferResultState string

// AcceptCallingOfferResultStatus defines model for AcceptCallingOfferResult.Status.
type AcceptCallingOfferResultStatus string

// AccessDiscovery defines model for AccessDiscovery.
type AccessDiscovery struct {
	Actor            Actor            `json:"actor"`
	PlatformOperator bool             `json:"platformOperator"`
	Practices        []PracticeAccess `json:"practices"`
}

// Actor defines model for Actor.
type Actor struct {
	Email   openapi_types.Email `json:"email"`
	Subject string              `json:"subject"`
	Type    ActorType           `json:"type"`
}

// ActorType defines model for Actor.Type.
type ActorType string

// AddLocationRequest defines model for AddLocationRequest.
type AddLocationRequest struct {
	Key              string             `json:"key"`
	Name             string             `json:"name"`
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action           string             `json:"action"`
	ActorSubject     string             `json:"actorSubject"`
	CreatedAt        time.Time          `json:"createdAt"`
	Id               openapi_types.UUID `json:"id"`
	PracticeId       openapi_types.UUID `json:"practiceId"`
	Reason           string             `json:"reason"`
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// Authorization defines model for Authorization.
type Authorization struct {
	ActiveLocation   *Location    `json:"activeLocation,omitempty"`
	Actor            Actor        `json:"actor"`
	Locations        []Location   `json:"locations"`
	Membership       *Membership  `json:"membership,omitempty"`
	PlatformOperator bool         `json:"platformOperator"`
	Practice         Practice     `json:"practice"`
	SupportMode      *SupportMode `json:"supportMode,omitempty"`
}

// CallHistoryItem defines model for CallHistoryItem.
type CallHistoryItem struct {
	AnsweredByEmail string                   `json:"answeredByEmail"`
	Current         bool                     `json:"current"`
	Direction       CallHistoryItemDirection `json:"direction"`
	DurationSeconds int64                    `json:"durationSeconds"`
	EndedAt         *time.Time               `json:"endedAt,omitempty"`
	Id              openapi_types.UUID       `json:"id"`
	LocationId      openapi_types.UUID       `json:"locationId"`
	LocationName    string                   `json:"locationName"`
	Originating     bool                     `json:"originating"`
	Outcome         CallHistoryItemOutcome   `json:"outcome"`
	StartedAt       time.Time                `json:"startedAt"`
	TransferReason  string                   `json:"transferReason"`
	Type            CallHistoryItemType      `json:"type"`
}

// CallHistoryItemDirection defines model for CallHistoryItem.Direction.
type CallHistoryItemDirection string

// CallHistoryItemOutcome defines model for CallHistoryItem.Outcome.
type CallHistoryItemOutcome string

// CallHistoryItemType defines model for CallHistoryItem.Type.
type CallHistoryItemType string

// CallHistoryPage defines model for CallHistoryPage.
type CallHistoryPage struct {
	Items      []CallHistoryItem `json:"items"`
	NextCursor string            `json:"nextCursor"`
}

// CallingCall defines model for CallingCall.
type CallingCall struct {
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	Deadline    time.Time  `json:"deadline"`
	DisplayName string     `json:"displayName"`

	// ExpectedMediaToken Opaque token that identifies the exact WebRTC media leg for the current claim.
	ExpectedMediaToken string `json:"expectedMediaToken"`

	// ExpectedStaffLegId Empty until Telnyx identifies the one staff leg created for this claim.
	ExpectedStaffLegId  string             `json:"expectedStaffLegId"`
	Id                  openapi_types.UUID `json:"id"`
	LocationId          openapi_types.UUID `json:"locationId"`
	LocationName        string             `json:"locationName"`
	NameSource          string             `json:"nameSource"`
	Phone               string             `json:"phone"`
	PhoneSource         string             `json:"phoneSource"`
	PracticeId          openapi_types.UUID `json:"practiceId"`
	ProviderTermination string             `json:"providerTermination"`
	ReasonSource        string             `json:"reasonSource"`
	Recording           *CallingRecording  `json:"recording,omitempty"`
	State               CallingCallState   `json:"state"`
	TransferReason      string             `json:"transferReason"`
	Version             int64              `json:"version"`
}

// CallingCallState defines model for CallingCall.State.
type CallingCallState string

// CallingControlRequest defines model for CallingControlRequest.
type CallingControlRequest struct {
	SessionId string `json:"sessionId"`
}

// CallingDispositionRequest defines model for CallingDispositionRequest.
type CallingDispositionRequest struct {
	Outcome   CallingDispositionRequestOutcome `json:"outcome"`
	SessionId string                           `json:"sessionId"`
}

// CallingDispositionRequestOutcome defines model for CallingDispositionRequest.Outcome.
type CallingDispositionRequestOutcome string

// CallingDispositionResult defines model for CallingDispositionResult.
type CallingDispositionResult struct {
	Call   CallingCall         `json:"call"`
	TaskId *openapi_types.UUID `json:"taskId,omitempty"`
}

// CallingOffer defines model for CallingOffer.
type CallingOffer struct {
	Deadline       time.Time          `json:"deadline"`
	DisplayName    string             `json:"displayName"`
	Id             openapi_types.UUID `json:"id"`
	LocationId     openapi_types.UUID `json:"locationId"`
	LocationName   string             `json:"locationName"`
	NameSource     string             `json:"nameSource"`
	PracticeId     openapi_types.UUID `json:"practiceId"`
	ReasonSource   string             `json:"reasonSource"`
	State          CallingOfferState  `json:"state"`
	TransferReason string             `json:"transferReason"`
	Version        int64              `json:"version"`
}

// CallingOfferState defines model for CallingOffer.State.
type CallingOfferState string

// CallingOfferList defines model for CallingOfferList.
type CallingOfferList struct {
	Items []CallingOffer `json:"items"`
}

// CallingReadinessRequest defines model for CallingReadinessRequest.
type CallingReadinessRequest struct {
	AudioReady      bool   `json:"audioReady"`
	Available       bool   `json:"available"`
	MicrophoneReady bool   `json:"microphoneReady"`
	Registered      bool   `json:"registered"`
	SessionHealthy  bool   `json:"sessionHealthy"`
	SessionId       string `json:"sessionId"`
}

// CallingRecording defines model for CallingRecording.
type CallingRecording struct {
	FailureCode *string               `json:"failureCode,omitempty"`
	State       CallingRecordingState `json:"state"`
}

// CallingRecordingState defines model for CallingRecording.State.
type CallingRecordingState string

// ContactContextInput defines model for ContactContextInput.
type ContactContextInput struct {
	DisplayName    *string `json:"displayName,omitempty"`
	NameSource     *string `json:"nameSource,omitempty"`
	Phone          string  `json:"phone"`
	PhoneSource    *string `json:"phoneSource,omitempty"`
	ReasonSource   *string `json:"reasonSource,omitempty"`
	TransferReason *string `json:"transferReason,omitempty"`
}

// CreateHandoffRequest defines model for CreateHandoffRequest.
type CreateHandoffRequest struct {
	Contact        ContactContextInput `json:"contact"`
	IdempotencyKey string              `json:"idempotencyKey"`
	LocationId     openapi_types.UUID  `json:"locationId"`
	PracticeId     openapi_types.UUID  `json:"practiceId"`
	SourceCallId   string              `json:"sourceCallId"`
}

// EnterSupportModeRequest defines model for EnterSupportModeRequest.
type EnterSupportModeRequest struct {
	DurationMinutes int                `json:"durationMinutes"`
	PracticeId      openapi_types.UUID `json:"practiceId"`
	Reason          string             `json:"reason"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code          string `json:"code"`
		CorrelationId string `json:"correlationId"`
		Message       string `json:"message"`
		Retryable     bool   `json:"retryable"`
	} `json:"error"`
}

// Handoff defines model for Handoff.
type Handoff struct {
	ExpiresAt      time.Time          `json:"expiresAt"`
	Id             openapi_types.UUID `json:"id"`
	SipDestination string             `json:"sipDestination"`
}

// Health defines model for Health.
type Health struct {
	Role   HealthRole   `json:"role"`
	Status HealthStatus `json:"status"`
}

// HealthRole defines model for Health.Role.
type HealthRole string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// InvitationCredentialRequest defines model for InvitationCredentialRequest.
type InvitationCredentialRequest struct {
	Token string `json:"token"`
}

// InvitationPreview defines model for InvitationPreview.
type InvitationPreview struct {
	Email         openapi_types.Email             `json:"email"`
	ExpiresAt     *time.Time                      `json:"expiresAt,omitempty"`
	Kind          InvitationPreviewKind           `json:"kind"`
	LocationScope *InvitationPreviewLocationScope `json:"locationScope,omitempty"`
	Locations     []Location                      `json:"locations"`
	PracticeId    *openapi_types.UUID             `json:"practiceId,omitempty"`
	PracticeName  *string                         `json:"practiceName,omitempty"`
	Role          *InvitationPreviewRole          `json:"role,omitempty"`
}

// InvitationPreviewKind defines model for InvitationPreview.Kind.
type InvitationPreviewKind string

// InvitationPreviewLocationScope defines model for InvitationPreview.LocationScope.
type InvitationPreviewLocationScope string

// InvitationPreviewRole defines model for InvitationPreview.Role.
type InvitationPreviewRole string

// Location defines model for Location.
type Location struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// LocationMutation defines model for LocationMutation.
type LocationMutation struct {
	Audit           AuditEvent `json:"audit"`
	Location        Location   `json:"location"`
	PracticeVersion int64      `json:"practiceVersion"`
}

// MediaToken defines model for MediaToken.
type MediaToken struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// MediaTokenRequest defines model for MediaTokenRequest.
type MediaTokenRequest struct {
	SessionId string `json:"sessionId"`
}

// Membership defines model for Membership.
type Membership struct {
	Id            openapi_types.UUID      `json:"id"`
	LocationScope MembershipLocationScope `json:"locationScope"`
	Role          MembershipRole          `json:"role"`
}

// MembershipLocationScope defines model for Membership.LocationScope.
type MembershipLocationScope string

// MembershipRole defines model for Membership.Role.
type MembershipRole string

// NavigationItem defines model for NavigationItem.
type NavigationItem struct {
	Enabled bool             `json:"enabled"`
	Id      NavigationItemId `json:"id"`
	Label   string           `json:"label"`
}

// NavigationItemId defines model for NavigationItem.Id.
type NavigationItemId string

// OperatorCallingTimeline defines model for OperatorCallingTimeline.
type OperatorCallingTimeline struct {
	CallId     openapi_types.UUID             `json:"callId"`
	Entries    []OperatorCallingTimelineEntry `json:"entries"`
	PracticeId openapi_types.UUID             `json:"practiceId"`
	State      OperatorCallingTimelineState   `json:"state"`
	Version    int64                          `json:"version"`
}

// OperatorCallingTimelineState defines model for OperatorCallingTimeline.State.
type OperatorCallingTimelineState string

// OperatorCallingTimelineEntry defines model for OperatorCallingTimelineEntry.
type OperatorCallingTimelineEntry struct {
	AgeSeconds      int64     `json:"ageSeconds"`
	CommandAction   string    `json:"commandAction"`
	CommandAttempts int       `json:"commandAttempts"`
	CommandState    string    `json:"commandState"`
	ErrorCode       string    `json:"errorCode"`
	Kind            string    `json:"kind"`
	OccurredAt      time.Time `json:"occurredAt"`
	OpaqueReference string    `json:"opaqueReference"`
	ReceiptState    string    `json:"receiptState"`
}

// Practice defines model for Practice.
type Practice struct {
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`
	Version int64              `json:"version"`
}

// PracticeAccess defines model for PracticeAccess.
type PracticeAccess struct {
	Id         openapi_types.UUID `json:"id"`
	Locations  []Location         `json:"locations"`
	Membership *Membership        `json:"membership,omitempty"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
}

// RenameTaskRequest defines model for RenameTaskRequest.
type RenameTaskRequest struct {
	ExpectedVersion  int64               `json:"expectedVersion"`
	SupportSessionId *openapi_types.UUID `json:"supportSessionId,omitempty"`
	Title            string              `json:"title"`
}

// SignUpEligibilityRequest defines model for SignUpEligibilityRequest.
type SignUpEligibilityRequest struct {
	Email           openapi_types.Email `json:"email"`
	InvitationToken *string             `json:"invitationToken,omitempty"`
}

// SoftphoneLeaseRequest defines model for SoftphoneLeaseRequest.
type SoftphoneLeaseRequest struct {
	SessionId string `json:"sessionId"`
	Takeover  bool   `json:"takeover"`
}

// SoftphoneState defines model for SoftphoneState.
type SoftphoneState struct {
	// ActiveCallId The User's current durable Call, or empty when capacity is free.
	ActiveCallId   string    `json:"activeCallId"`
	Available      bool      `json:"available"`
	LeaseExpiresAt time.Time `json:"leaseExpiresAt"`
	Owner          bool      `json:"owner"`
	SessionId      string    `json:"sessionId"`
}

// SupportMode defines model for SupportMode.
type SupportMode struct {
	ExpiresAt  time.Time          `json:"expiresAt"`
	Id         openapi_types.UUID `json:"id"`
	PracticeId openapi_types.UUID `json:"practiceId"`
	Reason     string             `json:"reason"`
	StartsAt   time.Time          `json:"startsAt"`
}

// Task defines model for Task.
type Task struct {
	CallId       openapi_types.UUID `json:"callId"`
	CompletedAt  *time.Time         `json:"completedAt,omitempty"`
	CompletedBy  *TaskActor         `json:"completedBy,omitempty"`
	CreatedAt    time.Time          `json:"createdAt"`
	CreatedBy    TaskActor          `json:"createdBy"`
	Id           openapi_types.UUID `json:"id"`
	LocationId   openapi_types.UUID `json:"locationId"`
	LocationName string             `json:"locationName"`
	Phone        string             `json:"phone"`
	PracticeId   openapi_types.UUID `json:"practiceId"`
	State        TaskState          `json:"state"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updatedAt"`
	Version      int64              `json:"version"`
}

// TaskState defines model for Task.State.
type TaskState string

// TaskActor defines model for TaskActor.
type TaskActor struct {
	Email   openapi_types.Email `json:"email"`
	Subject string              `json:"subject"`
}

// TaskPage defines model for TaskPage.
type TaskPage struct {
	Items      []Task `json:"items"`
	NextCursor string `json:"nextCursor"`
}

// TaskQueryRequest defines model for TaskQueryRequest.
type TaskQueryRequest struct {
	Cursor     *string             `json:"cursor,omitempty"`
	Limit      *int                `json:"limit,omitempty"`
	LocationId *openapi_types.UUID `json:"locationId,omitempty"`
	PracticeId openapi_types.UUID  `json:"practiceId"`
	Search     *string             `json:"search,omitempty"`
}

// TaskTransitionRequest defines model for TaskTransitionRequest.
type TaskTransitionRequest struct {
	ExpectedVersion  int64               `json:"expectedVersion"`
	SupportSessionId *openapi_types.UUID `json:"supportSessionId,omitempty"`
}

// WorkspaceSnapshot defines model for WorkspaceSnapshot.
type WorkspaceSnapshot struct {
	Actor            Actor                          `json:"actor"`
	Location         Location                       `json:"location"`
	Membership       *Membership                    `json:"membership,omitempty"`
	Navigation       []NavigationItem               `json:"navigation"`
	PlatformOperator bool                           `json:"platformOperator"`
	Practice         Practice                       `json:"practice"`
	SchemaVersion    WorkspaceSnapshotSchemaVersion `json:"schemaVersion"`
	State            WorkspaceSnapshotState         `json:"state"`
	SupportMode      *SupportMode                   `json:"supportMode,omitempty"`
	Version          int64                          `json:"version"`
}

// WorkspaceSnapshotSchemaVersion defines model for WorkspaceSnapshot.SchemaVersion.
type WorkspaceSnapshotSchemaVersion string

// WorkspaceSnapshotState defines model for WorkspaceSnapshot.State.
type WorkspaceSnapshotState string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// Denied defines model for Denied.
type Denied = ErrorEnvelope

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = ErrorEnvelope

// Unavailable defines model for Unavailable.
type Unavailable = ErrorEnvelope

// GetCallingCallHistoryParams defines parameters for GetCallingCallHistory.
type GetCallingCallHistoryParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	PracticeId openapi_types.UUID `form:"practiceId" json:"practiceId"`
	LocationId openapi_types.UUID `form:"locationId" json:"locationId"`
}

// ReceiveTelnyxWebhookJSONBody defines parameters for ReceiveTelnyxWebhook.
type ReceiveTelnyxWebhookJSONBody map[string]interface{}

// GetTaskCallHistoryParams defines parameters for GetTaskCallHistory.
type GetTaskCallHistoryParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	PracticeId openapi_types.UUID `form:"practiceId" json:"practiceId"`
	LocationId openapi_types.UUID `form:"locationId" json:"locationId"`
}

// InspectSignUpEligibilityJSONRequestBody defines body for InspectSignUpEligibility for application/json ContentType.
type InspectSignUpEligibilityJSONRequestBody = SignUpEligibilityRequest

// RecordCallingDispositionJSONRequestBody defines body for RecordCallingDisposition for application/json ContentType.
type RecordCallingDispositionJSONRequestBody = CallingDispositionRequest

// RequestCallingHangupJSONRequestBody defines body for RequestCallingHangup for application/json ContentType.
type RequestCallingHangupJSONRequestBody = CallingControlRequest

// IssueCallingMediaTokenJSONRequestBody defines body for IssueCallingMediaToken for application/json ContentType.
type IssueCallingMediaTokenJSONRequestBody = MediaTokenRequest

// AcceptCallingOfferJSONRequestBody defines body for AcceptCallingOffer for application/json ContentType.
type AcceptCallingOfferJSONRequestBody = AcceptCallingOfferRequest

// SetCallingReadinessJSONRequestBody defines body for SetCallingReadiness for application/json ContentType.
type SetCallingReadinessJSONRequestBody = CallingReadinessRequest

// AcquireSoftphoneJSONRequestBody defines body for AcquireSoftphone for application/json ContentType.
type AcquireSoftphoneJSONRequestBody = SoftphoneLeaseRequest

// CreateHandoffJSONRequestBody defines body for CreateHandoff for application/json ContentType.
type CreateHandoffJSONRequestBody = CreateHandoffRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationCredentialRequest

// InspectInvitationJSONRequestBody defines body for InspectInvitation for application/json ContentType.
type InspectInvitationJSONRequestBody = InvitationCredentialRequest

// AddLocationJSONRequestBody defines body for AddLocation for application/json ContentType.
type AddLocationJSONRequestBody = AddLocationRequest

// ReceiveTelnyxWebhookJSONRequestBody defines body for ReceiveTelnyxWebhook for application/json ContentType.
type ReceiveTelnyxWebhookJSONRequestBody ReceiveTelnyxWebhookJSONBody

// EnterSupportModeJSONRequestBody defines body for EnterSupportMode for application/json ContentType.
type EnterSupportModeJSONRequestBody = EnterSupportModeRequest

// QueryTasksJSONRequestBody defines body for QueryTasks for application/json ContentType.
type QueryTasksJSONRequestBody = TaskQueryRequest

// CompleteTaskJSONRequestBody defines body for CompleteTask for application/json ContentType.
type CompleteTaskJSONRequestBody = TaskTransitionRequest

// ReopenTaskJSONRequestBody defines body for ReopenTask for application/json ContentType.
type ReopenTaskJSONRequestBody = TaskTransitionRequest

// RenameTaskJSONRequestBody defines body for RenameTask for application/json ContentType.
type RenameTaskJSONRequestBody = RenameTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// DiscoverAccess Discover current Practice and Location authorization.
	// (GET /v1/access)
	DiscoverAccess(w http.ResponseWriter, r *http.Request)
	// InspectSignUpEligibility Validate an invitation or provisioned Platform Operator email.
	// (POST /v1/access/sign-up-eligibility)
	InspectSignUpEligibility(w http.ResponseWriter, r *http.Request)
	// GetCallingCall Read the winning User's durable active or disposition Call.
	// (GET /v1/calling/calls/{callId})
	GetCallingCall(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RecordCallingDisposition Resolve the provider-terminated Call and optionally ensure its one follow-up Task.
	// (POST /v1/calling/calls/{callId}/disposition)
	RecordCallingDisposition(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RequestCallingHangup Commit a provider hangup command without claiming termination.
	// (POST /v1/calling/calls/{callId}/hangup)
	RequestCallingHangup(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// GetCallingCallHistory Read authorized exact-phone Call Engagement History for the active Call.
	// (GET /v1/calling/calls/{callId}/history)
	GetCallingCallHistory(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID, params GetCallingCallHistoryParams)
	// IssueCallingMediaToken Issue a short-lived Telnyx JWT to the current softphone owner.
	// (POST /v1/calling/media-token)
	IssueCallingMediaToken(w http.ResponseWriter, r *http.Request)
	// ListCallingOffers List every current offer the User may accept now.
	// (GET /v1/calling/offers)
	ListCallingOffers(w http.ResponseWriter, r *http.Request)
	// AcceptCallingOffer Atomically claim one current offer and commit its Dial command.
	// (POST /v1/calling/offers/{callId}/accept)
	AcceptCallingOffer(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// SetCallingReadiness Commit the media-owning session's current technical readiness.
	// (PUT /v1/calling/readiness)
	SetCallingReadiness(w http.ResponseWriter, r *http.Request)
	// AcquireSoftphone Acquire, renew, or explicitly take over the User's softphone lease.
	// (POST /v1/calling/softphone/lease)
	AcquireSoftphone(w http.ResponseWriter, r *http.Request)
	// GetEvents Stream disposable version hints for one authorized scope.
	// (GET /v1/events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// CreateHandoff Create one authenticated, idempotent Abita handoff.
	// (POST /v1/handoffs)
	CreateHandoff(w http.ResponseWriter, r *http.Request)
	// AcceptInvitation Atomically activate an invitation for the verified identity.
	// (POST /v1/invitations/accept)
	AcceptInvitation(w http.ResponseWriter, r *http.Request)
	// InspectInvitation Inspect only the scope attached to the presented invitation.
	// (POST /v1/invitations/inspect)
	InspectInvitation(w http.ResponseWriter, r *http.Request)
	// GetOperatorCallingTimeline Read one sanitized durable Call timeline as a Platform Operator.
	// (GET /v1/operator/calls/{callId}/timeline)
	GetOperatorCallingTimeline(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// AddLocation Add a Location as a Platform Operator in Support Mode.
	// (POST /v1/practices/{practiceId}/locations)
	AddLocation(w http.ResponseWriter, r *http.Request, practiceId openapi_types.UUID)
	// ReceiveTelnyxWebhook Verify and durably receipt one raw Telnyx webhook.
	// (POST /v1/provider/telnyx/webhooks)
	ReceiveTelnyxWebhook(w http.ResponseWriter, r *http.Request)
	// EnterSupportMode Enter time-limited Support Mode for one Practice.
	// (POST /v1/support-mode)
	EnterSupportMode(w http.ResponseWriter, r *http.Request)
	// RevokeSupportMode Revoke the real operator's active Support Mode.
	// (DELETE /v1/support-mode/{supportSessionId})
	RevokeSupportMode(w http.ResponseWriter, r *http.Request, supportSessionId openapi_types.UUID)
	// QueryTasks Query the authorized Task rail with protected search input.
	// (POST /v1/tasks/query)
	QueryTasks(w http.ResponseWriter, r *http.Request)
	// ReadTask Read one currently authorized Task.
	// (GET /v1/tasks/{taskId})
	ReadTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// CompleteTask Complete one Task at its last observed version.
	// (POST /v1/tasks/{taskId}/complete)
	CompleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// GetTaskCallHistory Read authorized exact-phone Call Engagement History for one Task.
	// (GET /v1/tasks/{taskId}/history)
	GetTaskCallHistory(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID, params GetTaskCallHistoryParams)
	// ReopenTask Reopen one completed Task at its last observed version.
	// (POST /v1/tasks/{taskId}/reopen)
	ReopenTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// RenameTask Rename one open Task at its last observed version.
	// (PUT /v1/tasks/{taskId}/title)
	RenameTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// GetWorkspace Load the authoritative empty workspace snapshot.
	// (GET /v1/workspace)
	GetWorkspace(w http.ResponseWriter, r *http.Request, params GetWorkspaceParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverAccess operation middleware
func (siw *ServerInterfaceWrapper) DiscoverAccess(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectSignUpEligibility operation middleware
func (siw *ServerInterfaceWrapper) InspectSignUpEligibility(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectSignUpEligibility(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCallingCall operation middleware
func (siw *ServerInterfaceWrapper) GetCallingCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCallingCall(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordCallingDisposition operation middleware
func (siw *ServerInterfaceWrapper) RecordCallingDisposition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordCallingDisposition(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestCallingHangup operation middleware
func (siw *ServerInterfaceWrapper) RequestCallingHangup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestCallingHangup(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCallingCallHistory operation middleware
func (siw *ServerInterfaceWrapper) GetCallingCallHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCallingCallHistoryParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCallingCallHistory(w, r, callId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IssueCallingMediaToken operation middleware
func (siw *ServerInterfaceWrapper) IssueCallingMediaToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IssueCallingMediaToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCallingOffers operation middleware
func (siw *ServerInterfaceWrapper) ListCallingOffers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCallingOffers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptCallingOffer operation middleware
func (siw *ServerInterfaceWrapper) AcceptCallingOffer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptCallingOffer(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCallingReadiness operation middleware
func (siw *ServerInterfaceWrapper) SetCallingReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCallingReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcquireSoftphone operation middleware
func (siw *ServerInterfaceWrapper) AcquireSoftphone(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcquireSoftphone(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Required query parameter "practiceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "practiceId", r.URL.Query(), &params.PracticeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "practiceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "locationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locationId", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locationId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHandoff operation middleware
func (siw *ServerInterfaceWrapper) CreateHandoff(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHandoff(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectInvitation operation middleware
func (siw *ServerInterfaceWrapper) InspectInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperatorCallingTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetOperatorCallingTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperatorCallingTimeline(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddLocation operation middleware
func (siw *ServerInterfaceWrapper) AddLocation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "practiceId" -------------
	var practiceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "practiceId", r.PathValue("practiceId"), &practiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddLocation(w, r, practiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveTelnyxWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveTelnyxWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveTelnyxWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnterSupportMode operation middleware
func (siw *ServerInterfaceWrapper) EnterSupportMode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnterSupportMode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSupportMode operation middleware
func (siw *ServerInterfaceWrapper) RevokeSupportMode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "supportSessionId" -------------
	var supportSessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "supportSessionId", r.PathValue("supportSessionId"), &supportSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "supportSessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSupportMode(w, r, supportSessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryTasks operation middleware
func (siw *ServerInterfaceWrapper) QueryTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadTask operation middleware
func (siw *ServerInterfaceWrapper) ReadTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTask operation middleware
func (siw *ServerInterfaceWrapper) CompleteTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskCallHistory operation middleware
func (siw *ServerInterfaceWrapper) GetTaskCallHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTaskCallHistoryParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskCallHistory(w, r, taskId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReopenTask operation middleware
func (siw *ServerInterfaceWrapper) ReopenTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReopenTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameTask operation middleware
func (siw *ServerInterfaceWrapper) RenameTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Required query parameter "practiceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "practiceId", r.URL.Query(), &params.PracticeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "practiceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "locationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locationId", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locationId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.GetReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/access/sign-up-eligibility", wrapper.InspectSignUpEligibility)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/access", wrapper.DiscoverAccess)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/invitations/inspect", wrapper.InspectInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/invitations/accept", wrapper.AcceptInvitation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspace", wrapper.GetWorkspace)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/support-mode", wrapper.EnterSupportMode)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/support-mode/{supportSessionId}", wrapper.RevokeSupportMode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/practices/{practiceId}/locations", wrapper.AddLocation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.GetEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/handoffs", wrapper.CreateHandoff)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/provider/telnyx/webhooks", wrapper.ReceiveTelnyxWebhook)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/softphone/lease", wrapper.AcquireSoftphone)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/calling/readiness", wrapper.SetCallingReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/media-token", wrapper.IssueCallingMediaToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/offers", wrapper.ListCallingOffers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/offers/{callId}/accept", wrapper.AcceptCallingOffer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/calls/{callId}", wrapper.GetCallingCall)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/calls/{callId}/hangup", wrapper.RequestCallingHangup)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/calls/{callId}/disposition", wrapper.RecordCallingDisposition)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/calls/{callId}/history", wrapper.GetCallingCallHistory)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks/query", wrapper.QueryTasks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tasks/{taskId}", wrapper.ReadTask)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/tasks/{taskId}/title", wrapper.RenameTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks/{taskId}/complete", wrapper.CompleteTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tasks/{taskId}/reopen", wrapper.ReopenTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tasks/{taskId}/history", wrapper.GetTaskCallHistory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/operator/calls/{callId}/timeline", wrapper.GetOperatorCallingTimeline)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1bc9rItvBf6dK3q/bDB8bJZGZq/EZsMmEfbDOGJGdXJifVlhbQ21K3pruFzUn5v5/qi+4tQASInclT",
	"giW1Vq/7rZe+eD6LYkaBSuGdffE4iJhRAfrHaxzcwF8JCKl++YxKoPq/OI5D4mNJGO39RzCq/ib8BURY",
	"/e8fHGbemff/evnSPXNV9AacMz6gSwhZDN7j42PHC0D4nMRqMe/MG9IlDkmAuHnxiffY8c4ZnYXEPyIU",
	"0wWkEECAJMdUEHUJEYEoQyGjc+AILzEJ8W0IGsoLoASC48F4nnAOVCISAJVErlCI/TuBZAl0nMgF40Su",
	"NIjvqPqtbvexPCasl0QIQueIcUQsgX0OGnAcpqCl2DweWH2NKcIhQAHEQAOg/krRWEIUM445CVcooUU6",
	"P3bsy7WE9H0fYnmOw5DQ+fVsBrwgMDgINNPgcMxZDFwSJVYzHAroeHHhT188AUIQRoeaJBF+GAGdy4V3",
	"9vL0tONFhKa/X3Q8uYrBO/OE5ITONTzpHryzj4WFPmW3stv/gC8Vkl3giiRsC62Pw9CAOmM8wtI785KE",
	"BF4NuI4nJJaaoECTSAF4/ebN4GZ49bvX8c6vr64G59PSj8GF1/FuBufXV+fDkbny7qp/NfkwuNGXrgaD",
	"i8nni+FkfD0ZTofXV/r2yfXovb785no0uv7w+d34883gj3dD9cynBqgSUQSrf34+GJu390c3g/7Fvz+f",
	"j/rDS/2XwX+Ph+b1w6vBaPj78PVo4Fi3Sgrzkk6KrhQZTYQR4oIIny2Br1rSA/uS8U3C0Nc3PXa8OMRS",
	"0e06Bo7tgxagW8ZCwFTfxbEviW9eQCREYtMLxvYJsxe1hl0Vc45XNfQYoB3gFN/txpUFugWGIMIkLDGs",
	"+YuLNxLzphwr+TXzh5xr3r677CsOHI/60zfXN5efr8eDm/70+mYL7rCv6ZQhcW44CEbMKMDdtMsdrCp6",
	"5cVGvdLxKI6gtTpS+ItjxuWkqNE2qIkaaiordPQOLERODCUBkYNlajBaSQ4xFqW2D82fkzXM4HNQRrQv",
	"SzsMsISuJBG4eItspzRT/t9Sx3LAomETX08MfUsJFyX4Oi5qWaxmkBVx5SafdlL+F6fEaEnBJaTysUlH",
	"ZfelBN5aa4b2ye31YfFdZU3Y8SKIboGLBYk3rXKZ39lad2+rsQuccsmCjY9NCrc2avV06SLmHPC72EH5",
	"J2+JkIyvhhKitgxBxT1wCF6vBqnSr4uucZ3d2AsIh0wtpJp+ePX6+t2V25sIEq43OAGf0UCUZIxQ+csr",
	"TytNEqmlTrMFCJUwB81cyvM8hCJJUT9sd/uV1fy1Gxgnc0KxVD+duGOJ9Fn0JB0+3lJX66BPe8iN2rXq",
	"Dpz3R6PNlj/HfZHXijDWWapEygqhOjWWrwGfEybn/TI1N8jhGM+hpRxmOnIrZVmVeYfOpPAgzxMuSlqv",
	"Ccf6naVnmnZI6Fz90zYEYpSC35KlAsBBSCi0eIKIOMSrRoGEh1hDcQkBwVN2B5pRy0HudYz/SgBJdRXJ",
	"BU4zBjMCJlsAD9iX6APc3kzPUaRWQiHM0YxxfdkyDPJDTKITF5QpFBOJZ7MRzI26KUMxiGKpYmlJQjSF",
	"kK4eqmAwCkioFfTbrcdgoSBizeu/kTJU3uiEJdx3X44XjK65su7Jdu5fzNmSBMCnwCMtzg3ayjhja97L",
	"wWc8sLp9k7ASOr/J7ncF+t9O2W+huZfAhcVTs6l+UTfVLlVe8obXqWmDooIaSJmkzBJlqS/xmUOxl6jq",
	"FEWnlnCzTY6YddqSUclZ+KQTXRbUCyJiZjK3u4Hr8Gd2cD5Ke95pj7kB33a3O6b1thR9bTGVqGFxt0tU",
	"qV+1Zis6N9kS/P1b1ydqWHbJDqxZrzlF+5yU61fozII+TlX0FmpQs+iItFYp7f3iTB42pVTNimtgvgEc",
	"EApC7KYNcRIQptZYuaO/UgWnfjkiPmfa0q1Zg8OcCAncVKfq161OfAs4lIvV2nv2aWRKgNW30inipgZk",
	"ETNrqVPwv1qQZYZJmHA4t6mbzQI+vJoOri4yZ+zmwrhiuuyhzFp/OHKaMkeBo2FDjErsS/UPPMghjZO2",
	"rFZRzVUibtCZ1Ux3s3MeYymBqwDlf/788/9/fNH97dPH0+5vn7782nnx6vEfXmej+77xXVUFvPGBuoot",
	"PPKz45EKXczmnHTRQdVbTAM2m+2mA3xD2o16y8EB2qJCFDMJ1F/9V60osU11oaWtbWkrhSbSeVbe/Brd",
	"0Wy5Sm+p4aSTodhFwQGVwAsJ2N2ImKaXLglNpPlThB+MYX756nS9mf6K+kSVj3fGZ1ZYqO7EibNSG0DL",
	"wqF6trWINChin3EOYYF/a3dEIIRNtTnQKPmqybpW/WsFQr5c9dXFxeoYq6xlUOBCrFUkbVH6EBMO4gDp",
	"bkHiCxCyOQni8jArD3UK8Dn3rG16yy1zFpYMsJJeHHZxTAqBeJfQOQchDHuHGhfbNS+wuxbdCBoW186G",
	"dEmkRsJ51pqzm3qRaSKyqD9//qUk7z+93ASxWWU9pGMOSwL3h+sG2IFZ7wgNitQZ3/TPp8Pzwefh1fvh",
	"tG/TWtu0DOR2Y+KzcqmhPxp5HW8yGJms2rpn91OxbJ2UNLc3BrlVkehfXA4VXibT/ps3m9lZIznvncj3",
	"6uKXYnW4TaS23Vape4suXdPYwJBCeJnInYrgSUA2umSFJokCd7ThiZSo79cE+BuC+uy19dU6dhsu/JTr",
	"G4c1Npn22kY9bTIXOeBPOl96WepH2L+MfI0e+0pNoQHSa1TBcCHiCi/J3LhJ7VsPgCqPqiFxQUpGQWJx",
	"l/YGdn1QXr1XqMAInUSQUv/XqdzxLYRbah1zbycDz7XvtCHDpiKmJII0l3qYxlCgkpMW3YUNAA6o5Ks9",
	"2Kun2ae6p0xq1oBabtyq5DpzmrRgEIP/ltZqDru3yvgsijAN+s2Ne+kdUkIUm1MNWy05SVmgzqsqAmpM",
	"r6X+Xr1bxtel81YtAkwX629gBhxoc50WSCyb4HV7StWFi7uqYrWCkjpKKzB0iiQt7dvFSeNCd9rRvLH9",
	"ViWoqTKsqxJUuqHVXsPweuadfdy6J68Vep5Cf2KDr+dSKJ8eO94NKDxOsbjbzTdKy9rvd6TsTu2xHU8S",
	"GcLXZrOqsKfLulhpQub0XTwIyZzckpDI1Y7oaox6Cxv56aUrI02ygHu6l9DevNi5VzaTOn89Aizg2D5z",
	"x5P4DtgS+BY5tmJxKHts7Z4yjd26vzlPSdfPqb0TwP8psjatIOHKzUPqkQ5iHIHuvLpfAEU+jrFPpD7i",
	"NOMAznaqDVW8UBFm0D6sYvcU+Bb1uu0rchVI0lcUd9Ap489JnXLj85NIZO7xAIDEXLYAcWMNPsu8Zytv",
	"CoGVgj9cHKFMUggtGzGzh16vNtk3BX12CGCHIx/2kZYv+kadJ2t6Fr82nBoPrnT0dDkeDZoi/cyy1q4k",
	"cdAW8d+kCyWPtGxjn9lSHmzl7FDkpmIQlm+1SZi+2QG4DUfYmuA9ePO41jDH6RhXr/ojAb6jD+Y3QdPx",
	"QhKZHG5Wif15YyH2wNVwwNxf7NB/kL+mCYXT7ET9M3L9N7jwrr1+YPxOxNiHCcWxWDB50JO9u+T0dz2J",
	"RrNE6dZiWsmtupJ2hzvepv9WYJfUML08fflL9/TX7stXjcXWkiEbXI6n/3bfuuMJur2ZqvIeizYltT5r",
	"Tud5JZJudVJPqwg/4USuJurVhmVvAXPg/cQUyc2vN+mu/vVh6lliaKLqq7mkLaSMjebhS+LDa3O5voxJ",
	"ZnXtbd20FLNh3Ucdyc5YPYzq+4mKisa6LI9MygZhGqC3SYSpTXkihXc+wz4IdE/kAo2ZkHMOkz9G+ZiN",
	"ThZ/2UMuNnVmlrNZM9HRvwLdr61vTgv+aEGoFCd/5gmBGnDjYYG0Zzn//mrSh0BxTLwz76eT05OfFB2x",
	"XGi69Ba6c6EXkqXmzzloZcQ0fa0K9H4HOSJLoGkbQmEYzMvT070N5rBNFI6JHGPONPKJQDyhlND5SYnR",
	"vLOPn9TvdDc87SRt2k7W8vpt9nOTzhfhCdUEzuaMEBAIc036wExn+fn0p6YXZZD3inNSnIhZvujhLOfo",
	"xEo6ZsKmJg+Il+pYizVTbFKhSwUJzTiLCiKmMfTq9MVWGCoNudHPbYFZO79nZ0IkUYT5qoDfLCWTGiIt",
	"9anxTbdqTr0bLs+J1xNkTrtJ3IU87af7VZlwUHRIhfJFaolCzxgIEPI1M2KyF7I2JiQfyyZJ8gQeD8he",
	"9T6ghlFOS+BkRiDo6kAFWdwqJWPQayc4HYVNCvJaZJr3OCQq8EOYojzdihhHuj9MaXsI0NhaZZSaZaR3",
	"lHOPb2yV/lf0vph49HGdgiye6FHmguMIJHChKxVEYVCZkLTocZaHuGU6dwo02+RHfzogT5QOKDkmPlmh",
	"g0AnSNF96qA/I/2iTJo+MXtPtIVMM8Cp52FSnop1gvxEmN7uJj7pFR5o1jbmnEL90NlR2Wf/Wq35zOCR",
	"1VrjcT4HP19YmktzijM0XG0PC2p7w2ITa6KQ0DsIkAq/LbOfbubCwgjA48nHq9PfNt+eDQXch0AJFi5B",
	"y1TWjWsxKlNNUcRluEJARcIBESn0wfUZC0N2r4yKxe96OVtgOk/idSKmcW454a25+7sQr8rp4a1E6+Wx",
	"rINBtA70qNShG5ESgpPvmPfP9SYRzhgfGd5MA1cd6rLEjn9Q1kbmB8Y387kZ6bGl/2EHgByL0Tt24b8S",
	"4KvCyiZHW1zp2A5MceqKg02v4B6ERDGeK30FAqjSUoQif8EZZSGbEx+HiPEA+BNX9ftwhXDu0+lRJl1d",
	"fDFae0DneA6REmeL1GyuiXWT3H6RHoPSzVqBG8IuIRKw/FuarXAI/VnvJD6yW1LYoYMnJwvGZTckSwjQ",
	"LWf3AridJVMZ9PrD7UiZV7MPwkgUUGezhv/6MEWSlcbviLSLBOk2hzrLstlM68sGVTsiojT59aCJn9oZ",
	"eQfHDDAPCQjZTc/fd2eEC5mlgLCJYjSszyg6U9tFsAS+ykin96CJ+U6LBV4hrCfxIsrumwiZG1Fzb7Ma",
	"qk/1feauYvNU5SOrvMZ5ya5EZuotWtpi6usYHB7U24lEIdMjsLle4fs2y33JIuWChCvjNuoQqSwNyrU0",
	"DraOoS4IDlOXsy4RPEviKyFIHDIwyRzJcsL/YHFMbZTGkVmz0lS4JrMeANemJUMYDpEuCH7fPGgDG6V1",
	"jTPH7nWyzHYQFjomJfgLqj3mjM/qLJiZ355uO1ynjTULZPQ5VA7e2Sj7ZJmw4r2IBYm/cxVo2KCDOFC4",
	"7xQtQbhCEt8B0jUimXfw5jjSLJbzICzTz3M0BdEDc4fb7Ffi20o7556j51J33CFLBBIepMFMV0gOOCqz",
	"bXXBGme+ZgkNIEC1dU7QkBJp7JEe8qmLdTSwTh0H++f02xEI04rPmhUVEIcZSH9x8id9Ppw70VgodifY",
	"bgPTnKDjZ8WkhbBb+Cwu8OvCzIUQzUqyNIjmUIbaNexmKwX5Yn+NAXaHDv6zY1mVTxhCNxGAJsMxsqj7",
	"ESmXS6Vfqi1BHz89lsqnhtgZX2ab66BsvI5E/VsicQHFll3zcqvYMtbKC88H4t11sziOHQOVhvO7vu2T",
	"9QVqLelQC99tBqcQ5+hsYr1+nyYb0w6E7GtNbvYjppFjY6fH34kBt+ryGAMNTI9eevM37+iwpEKMKodv",
	"AUYcEJYS+wvleDBbcMwT+AXYLXMw2+dRLazIwgH9Jqew6Uz/d9Dl0bQ1V2IaK29OqaOswqXLWozfzUJ2",
	"j2yJ6rn1f+hp6dnWiof+UMobCAuE6y1DOXNl31nqfcmDgsde6ShxgxnMP0m0FTvtKeY4VL6x/oGlI/uJ",
	"tfk/axOMWQthZG+3hjcg33teMQgQLnRQOvkbEYpsgz26ZAEU+d0ogJ7UVZbePdwuGLsTa1udgCzBVGU+",
	"mNu/wuK6T34YKag212/Bf6/qnew3psPcKoRV3sOAGLeJaa0uDJQ7pwD32/qofKOVaYm3YNtGea3lOL5P",
	"y2KWYDlF7ZmLbmQPXbipWB2aeSCfqWk255F1SfnzTPUOSFP2rkjId6w0NFm0UezqM3YQlDaf5TPSLm03",
	"d/W+VE+MPRrpC8EcEKoqjiW7gzLPbTaTjm+p7dP/cuiLEia4Bjp4Vq6Qgth+8xaHKHWX/ynS9g63JdDj",
	"t3omddmoNvQ5z6kd1HUIhVE7THrkyCo7nOtMTwG1BXl1G+KYhLrj6PtWFpocpj0oz2PkCNDnvmLOpD75",
	"icwJWURonMgqc30x38Zo7r1Xbrw+ubyNZrAf2niq8Zg5gd1c/tEYLBYdn1WcZQuF4arKFE0076UDJtZk",
	"wO0dR+eAw6ix+oHub6DLGqImM+pDf3s8ywWHeXfOj4Z4V+1cI01zv5ZdbNo0QiwkYrcC+BKCtC7UKAVb",
	"dP+qxdu2/u5BEn60/v5tW39Tlm7kWg4shrXHn9T1H3r7sHrbYPmH2m4nEgpnxmXJzN7u6jsbx+TsuMun",
	"Nz5zMaiPoXwyIqAA+3Fiz8npCjWa0zXLt2DyrDlnnVuSze35W7VU7c7C9TlH689e5x1Swj7wnDr8mT1/",
	"Xe76snM2XTurdbMUh+TYVhbFrpbFKkd8IQ7ZKtINaomiEATo7XQ6niDzAW+v4yU8tFNuxFmvh2NygvXQ",
	"mBN4wMoOeI+fHv8vAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
