//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AcceptCallingOfferResultState.
const (
	AcceptCallingOfferResultStateCONNECTED        AcceptCallingOfferResultState = "CONNECTED"
	AcceptCallingOfferResultStateCONNECTING       AcceptCallingOfferResultState = "CONNECTING"
	AcceptCallingOfferResultStateFOLLOWUPREQUIRED AcceptCallingOfferResultState = "FOLLOW_UP_REQUIRED"
	AcceptCallingOfferResultStateNEEDSDISPOSITION AcceptCallingOfferResultState = "NEEDS_DISPOSITION"
	AcceptCallingOfferResultStateOFFERING         AcceptCallingOfferResultState = "OFFERING"
	AcceptCallingOfferResultStateRECONCILING      AcceptCallingOfferResultState = "RECONCILING"
	AcceptCallingOfferResultStateRESOLVED         AcceptCallingOfferResultState = "RESOLVED"
	AcceptCallingOfferResultStateUNANSWERED       AcceptCallingOfferResultState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the AcceptCallingOfferResultState enum.
func (e AcceptCallingOfferResultState) Valid() bool {
	switch e {
	case AcceptCallingOfferResultStateCONNECTED:
		return true
	case AcceptCallingOfferResultStateCONNECTING:
		return true
	case AcceptCallingOfferResultStateFOLLOWUPREQUIRED:
		return true
	case AcceptCallingOfferResultStateNEEDSDISPOSITION:
		return true
	case AcceptCallingOfferResultStateOFFERING:
		return true
	case AcceptCallingOfferResultStateRECONCILING:
		return true
	case AcceptCallingOfferResultStateRESOLVED:
		return true
	case AcceptCallingOfferResultStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for AcceptCallingOfferResultStatus.
const (
	ACCEPTED       AcceptCallingOfferResultStatus = "ACCEPTED"
	ALREADYCLAIMED AcceptCallingOfferResultStatus = "ALREADY_CLAIMED"
	EXPIRED        AcceptCallingOfferResultStatus = "EXPIRED"
	INELIGIBLE     AcceptCallingOfferResultStatus = "INELIGIBLE"
)

// Valid indicates whether the value is a known member of the AcceptCallingOfferResultStatus enum.
func (e AcceptCallingOfferResultStatus) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case ALREADYCLAIMED:
		return true
	case EXPIRED:
		return true
	case INELIGIBLE:
		return true
	default:
		return false
	}
}

// Defines values for ActorType.
const (
	ActorTypeHUMAN            ActorType = "HUMAN"
	ActorTypePLATFORMOPERATOR ActorType = "PLATFORM_OPERATOR"
)

// Valid indicates whether the value is a known member of the ActorType enum.
func (e ActorType) Valid() bool {
	switch e {
	case ActorTypeHUMAN:
		return true
	case ActorTypePLATFORMOPERATOR:
		return true
	default:
		return false
	}
}

// Defines values for CallingCallState.
const (
	CallingCallStateCONNECTED        CallingCallState = "CONNECTED"
	CallingCallStateCONNECTING       CallingCallState = "CONNECTING"
	CallingCallStateFOLLOWUPREQUIRED CallingCallState = "FOLLOW_UP_REQUIRED"
	CallingCallStateNEEDSDISPOSITION CallingCallState = "NEEDS_DISPOSITION"
	CallingCallStateRECONCILING      CallingCallState = "RECONCILING"
	CallingCallStateRESOLVED         CallingCallState = "RESOLVED"
	CallingCallStateUNANSWERED       CallingCallState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the CallingCallState enum.
func (e CallingCallState) Valid() bool {
	switch e {
	case CallingCallStateCONNECTED:
		return true
	case CallingCallStateCONNECTING:
		return true
	case CallingCallStateFOLLOWUPREQUIRED:
		return true
	case CallingCallStateNEEDSDISPOSITION:
		return true
	case CallingCallStateRECONCILING:
		return true
	case CallingCallStateRESOLVED:
		return true
	case CallingCallStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for CallingDispositionRequestOutcome.
const (
	CallingDispositionRequestOutcomeFOLLOWUPREQUIRED CallingDispositionRequestOutcome = "FOLLOW_UP_REQUIRED"
	CallingDispositionRequestOutcomeRESOLVED         CallingDispositionRequestOutcome = "RESOLVED"
)

// Valid indicates whether the value is a known member of the CallingDispositionRequestOutcome enum.
func (e CallingDispositionRequestOutcome) Valid() bool {
	switch e {
	case CallingDispositionRequestOutcomeFOLLOWUPREQUIRED:
		return true
	case CallingDispositionRequestOutcomeRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for CallingOfferState.
const (
	CallingOfferStateOFFERING CallingOfferState = "OFFERING"
)

// Valid indicates whether the value is a known member of the CallingOfferState enum.
func (e CallingOfferState) Valid() bool {
	switch e {
	case CallingOfferStateOFFERING:
		return true
	default:
		return false
	}
}

// Defines values for CallingRecordingState.
const (
	FAILED    CallingRecordingState = "FAILED"
	INTENDED  CallingRecordingState = "INTENDED"
	READY     CallingRecordingState = "READY"
	RECORDING CallingRecordingState = "RECORDING"
)

// Valid indicates whether the value is a known member of the CallingRecordingState enum.
func (e CallingRecordingState) Valid() bool {
	switch e {
	case FAILED:
		return true
	case INTENDED:
		return true
	case READY:
		return true
	case RECORDING:
		return true
	default:
		return false
	}
}

// Defines values for HealthRole.
const (
	PortalApi       HealthRole = "portal-api"
	ProviderIngress HealthRole = "provider-ingress"
	Realtime        HealthRole = "realtime"
)

// Valid indicates whether the value is a known member of the HealthRole enum.
func (e HealthRole) Valid() bool {
	switch e {
	case PortalApi:
		return true
	case ProviderIngress:
		return true
	case Realtime:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewKind.
const (
	InvitationPreviewKindPLATFORMOPERATOR   InvitationPreviewKind = "PLATFORM_OPERATOR"
	InvitationPreviewKindPRACTICEINVITATION InvitationPreviewKind = "PRACTICE_INVITATION"
)

// Valid indicates whether the value is a known member of the InvitationPreviewKind enum.
func (e InvitationPreviewKind) Valid() bool {
	switch e {
	case InvitationPreviewKindPLATFORMOPERATOR:
		return true
	case InvitationPreviewKindPRACTICEINVITATION:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewLocationScope.
const (
	InvitationPreviewLocationScopeALL      InvitationPreviewLocationScope = "ALL"
	InvitationPreviewLocationScopeSELECTED InvitationPreviewLocationScope = "SELECTED"
)

// Valid indicates whether the value is a known member of the InvitationPreviewLocationScope enum.
func (e InvitationPreviewLocationScope) Valid() bool {
	switch e {
	case InvitationPreviewLocationScopeALL:
		return true
	case InvitationPreviewLocationScopeSELECTED:
		return true
	default:
		return false
	}
}

// Defines values for InvitationPreviewRole.
const (
	InvitationPreviewRoleADMIN InvitationPreviewRole = "ADMIN"
	InvitationPreviewRoleSTAFF InvitationPreviewRole = "STAFF"
)

// Valid indicates whether the value is a known member of the InvitationPreviewRole enum.
func (e InvitationPreviewRole) Valid() bool {
	switch e {
	case InvitationPreviewRoleADMIN:
		return true
	case InvitationPreviewRoleSTAFF:
		return true
	default:
		return false
	}
}

// Defines values for MembershipLocationScope.
const (
	MembershipLocationScopeALL      MembershipLocationScope = "ALL"
	MembershipLocationScopeSELECTED MembershipLocationScope = "SELECTED"
)

// Valid indicates whether the value is a known member of the MembershipLocationScope enum.
func (e MembershipLocationScope) Valid() bool {
	switch e {
	case MembershipLocationScopeALL:
		return true
	case MembershipLocationScopeSELECTED:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRole.
const (
	MembershipRoleADMIN MembershipRole = "ADMIN"
	MembershipRoleSTAFF MembershipRole = "STAFF"
)

// Valid indicates whether the value is a known member of the MembershipRole enum.
func (e MembershipRole) Valid() bool {
	switch e {
	case MembershipRoleADMIN:
		return true
	case MembershipRoleSTAFF:
		return true
	default:
		return false
	}
}

// Defines values for NavigationItemId.
const (
	CallCenter NavigationItemId = "call-center"
	Recordings NavigationItemId = "recordings"
	Settings   NavigationItemId = "settings"
	Tasks      NavigationItemId = "tasks"
)

// Valid indicates whether the value is a known member of the NavigationItemId enum.
func (e NavigationItemId) Valid() bool {
	switch e {
	case CallCenter:
		return true
	case Recordings:
		return true
	case Settings:
		return true
	case Tasks:
		return true
	default:
		return false
	}
}

// Defines values for OperatorCallingTimelineState.
const (
	OperatorCallingTimelineStateCONNECTED        OperatorCallingTimelineState = "CONNECTED"
	OperatorCallingTimelineStateCONNECTING       OperatorCallingTimelineState = "CONNECTING"
	OperatorCallingTimelineStateFOLLOWUPREQUIRED OperatorCallingTimelineState = "FOLLOW_UP_REQUIRED"
	OperatorCallingTimelineStateNEEDSDISPOSITION OperatorCallingTimelineState = "NEEDS_DISPOSITION"
	OperatorCallingTimelineStateOFFERING         OperatorCallingTimelineState = "OFFERING"
	OperatorCallingTimelineStateRECONCILING      OperatorCallingTimelineState = "RECONCILING"
	OperatorCallingTimelineStateRESOLVED         OperatorCallingTimelineState = "RESOLVED"
	OperatorCallingTimelineStateUNANSWERED       OperatorCallingTimelineState = "UNANSWERED"
)

// Valid indicates whether the value is a known member of the OperatorCallingTimelineState enum.
func (e OperatorCallingTimelineState) Valid() bool {
	switch e {
	case OperatorCallingTimelineStateCONNECTED:
		return true
	case OperatorCallingTimelineStateCONNECTING:
		return true
	case OperatorCallingTimelineStateFOLLOWUPREQUIRED:
		return true
	case OperatorCallingTimelineStateNEEDSDISPOSITION:
		return true
	case OperatorCallingTimelineStateOFFERING:
		return true
	case OperatorCallingTimelineStateRECONCILING:
		return true
	case OperatorCallingTimelineStateRESOLVED:
		return true
	case OperatorCallingTimelineStateUNANSWERED:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSnapshotSchemaVersion.
const (
	N20260724 WorkspaceSnapshotSchemaVersion = "2026-07-24"
)

// Valid indicates whether the value is a known member of the WorkspaceSnapshotSchemaVersion enum.
func (e WorkspaceSnapshotSchemaVersion) Valid() bool {
	switch e {
	case N20260724:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSnapshotState.
const (
	EMPTY WorkspaceSnapshotState = "EMPTY"
)

// Valid indicates whether the value is a known member of the WorkspaceSnapshotState enum.
func (e WorkspaceSnapshotState) Valid() bool {
	switch e {
	case EMPTY:
		return true
	default:
		return false
	}
}

// AcceptCallingOfferRequest defines model for AcceptCallingOfferRequest.
type AcceptCallingOfferRequest struct {
	SessionId string `json:"sessionId"`
}

// AcceptCallingOfferResult defines model for AcceptCallingOfferResult.
type AcceptCallingOfferResult struct {
	CallId openapi_types.UUID             `json:"callId"`
	State  AcceptCallingOfferResultState  `json:"state"`
	Status AcceptCallingOfferResultStatus `json:"status"`
}

// AcceptCallingOfferResultState defines model for AcceptCallingOfferResult.State.
type AcceptCallingOfferResultState string

// AcceptCallingOfferResultStatus defines model for AcceptCallingOfferResult.Status.
type AcceptCallingOfferResultStatus string

// AccessDiscovery defines model for AccessDiscovery.
type AccessDiscovery struct {
	Actor            Actor            `json:"actor"`
	PlatformOperator bool             `json:"platformOperator"`
	Practices        []PracticeAccess `json:"practices"`
}

// Actor defines model for Actor.
type Actor struct {
	Email   openapi_types.Email `json:"email"`
	Subject string              `json:"subject"`
	Type    ActorType           `json:"type"`
}

// ActorType defines model for Actor.Type.
type ActorType string

// AddLocationRequest defines model for AddLocationRequest.
type AddLocationRequest struct {
	Key              string             `json:"key"`
	Name             string             `json:"name"`
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action           string             `json:"action"`
	ActorSubject     string             `json:"actorSubject"`
	CreatedAt        time.Time          `json:"createdAt"`
	Id               openapi_types.UUID `json:"id"`
	PracticeId       openapi_types.UUID `json:"practiceId"`
	Reason           string             `json:"reason"`
	SupportSessionId openapi_types.UUID `json:"supportSessionId"`
}

// Authorization defines model for Authorization.
type Authorization struct {
	ActiveLocation   *Location    `json:"activeLocation,omitempty"`
	Actor            Actor        `json:"actor"`
	Locations        []Location   `json:"locations"`
	Membership       *Membership  `json:"membership,omitempty"`
	PlatformOperator bool         `json:"platformOperator"`
	Practice         Practice     `json:"practice"`
	SupportMode      *SupportMode `json:"supportMode,omitempty"`
}

// CallingCall defines model for CallingCall.
type CallingCall struct {
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	Deadline    time.Time  `json:"deadline"`
	DisplayName string     `json:"displayName"`

	// ExpectedMediaToken Opaque token that identifies the exact WebRTC media leg for the current claim.
	ExpectedMediaToken string `json:"expectedMediaToken"`

	// ExpectedStaffLegId Empty until Telnyx identifies the one staff leg created for this claim.
	ExpectedStaffLegId  string             `json:"expectedStaffLegId"`
	Id                  openapi_types.UUID `json:"id"`
	LocationId          openapi_types.UUID `json:"locationId"`
	LocationName        string             `json:"locationName"`
	NameSource          string             `json:"nameSource"`
	Phone               string             `json:"phone"`
	PhoneSource         string             `json:"phoneSource"`
	PracticeId          openapi_types.UUID `json:"practiceId"`
	ProviderTermination string             `json:"providerTermination"`
	ReasonSource        string             `json:"reasonSource"`
	Recording           *CallingRecording  `json:"recording,omitempty"`
	State               CallingCallState   `json:"state"`
	TransferReason      string             `json:"transferReason"`
	Version             int64              `json:"version"`
}

// CallingCallState defines model for CallingCall.State.
type CallingCallState string

// CallingControlRequest defines model for CallingControlRequest.
type CallingControlRequest struct {
	SessionId string `json:"sessionId"`
}

// CallingDispositionRequest defines model for CallingDispositionRequest.
type CallingDispositionRequest struct {
	Outcome   CallingDispositionRequestOutcome `json:"outcome"`
	SessionId string                           `json:"sessionId"`
}

// CallingDispositionRequestOutcome defines model for CallingDispositionRequest.Outcome.
type CallingDispositionRequestOutcome string

// CallingOffer defines model for CallingOffer.
type CallingOffer struct {
	Deadline       time.Time          `json:"deadline"`
	DisplayName    string             `json:"displayName"`
	Id             openapi_types.UUID `json:"id"`
	LocationId     openapi_types.UUID `json:"locationId"`
	LocationName   string             `json:"locationName"`
	NameSource     string             `json:"nameSource"`
	PracticeId     openapi_types.UUID `json:"practiceId"`
	ReasonSource   string             `json:"reasonSource"`
	State          CallingOfferState  `json:"state"`
	TransferReason string             `json:"transferReason"`
	Version        int64              `json:"version"`
}

// CallingOfferState defines model for CallingOffer.State.
type CallingOfferState string

// CallingOfferList defines model for CallingOfferList.
type CallingOfferList struct {
	Items []CallingOffer `json:"items"`
}

// CallingReadinessRequest defines model for CallingReadinessRequest.
type CallingReadinessRequest struct {
	AudioReady      bool   `json:"audioReady"`
	Available       bool   `json:"available"`
	MicrophoneReady bool   `json:"microphoneReady"`
	Registered      bool   `json:"registered"`
	SessionHealthy  bool   `json:"sessionHealthy"`
	SessionId       string `json:"sessionId"`
}

// CallingRecording defines model for CallingRecording.
type CallingRecording struct {
	FailureCode *string               `json:"failureCode,omitempty"`
	State       CallingRecordingState `json:"state"`
}

// CallingRecordingState defines model for CallingRecording.State.
type CallingRecordingState string

// ContactContextInput defines model for ContactContextInput.
type ContactContextInput struct {
	DisplayName    *string `json:"displayName,omitempty"`
	NameSource     *string `json:"nameSource,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	PhoneSource    *string `json:"phoneSource,omitempty"`
	ReasonSource   *string `json:"reasonSource,omitempty"`
	TransferReason *string `json:"transferReason,omitempty"`
}

// CreateHandoffRequest defines model for CreateHandoffRequest.
type CreateHandoffRequest struct {
	Contact        ContactContextInput `json:"contact"`
	IdempotencyKey string              `json:"idempotencyKey"`
	LocationId     openapi_types.UUID  `json:"locationId"`
	PracticeId     openapi_types.UUID  `json:"practiceId"`
	SourceCallId   string              `json:"sourceCallId"`
}

// EnterSupportModeRequest defines model for EnterSupportModeRequest.
type EnterSupportModeRequest struct {
	DurationMinutes int                `json:"durationMinutes"`
	PracticeId      openapi_types.UUID `json:"practiceId"`
	Reason          string             `json:"reason"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code          string `json:"code"`
		CorrelationId string `json:"correlationId"`
		Message       string `json:"message"`
		Retryable     bool   `json:"retryable"`
	} `json:"error"`
}

// Handoff defines model for Handoff.
type Handoff struct {
	ExpiresAt      time.Time          `json:"expiresAt"`
	Id             openapi_types.UUID `json:"id"`
	SipDestination string             `json:"sipDestination"`
}

// Health defines model for Health.
type Health struct {
	Role   HealthRole   `json:"role"`
	Status HealthStatus `json:"status"`
}

// HealthRole defines model for Health.Role.
type HealthRole string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// InvitationCredentialRequest defines model for InvitationCredentialRequest.
type InvitationCredentialRequest struct {
	Token string `json:"token"`
}

// InvitationPreview defines model for InvitationPreview.
type InvitationPreview struct {
	Email         openapi_types.Email             `json:"email"`
	ExpiresAt     *time.Time                      `json:"expiresAt,omitempty"`
	Kind          InvitationPreviewKind           `json:"kind"`
	LocationScope *InvitationPreviewLocationScope `json:"locationScope,omitempty"`
	Locations     []Location                      `json:"locations"`
	PracticeId    *openapi_types.UUID             `json:"practiceId,omitempty"`
	PracticeName  *string                         `json:"practiceName,omitempty"`
	Role          *InvitationPreviewRole          `json:"role,omitempty"`
}

// InvitationPreviewKind defines model for InvitationPreview.Kind.
type InvitationPreviewKind string

// InvitationPreviewLocationScope defines model for InvitationPreview.LocationScope.
type InvitationPreviewLocationScope string

// InvitationPreviewRole defines model for InvitationPreview.Role.
type InvitationPreviewRole string

// Location defines model for Location.
type Location struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// LocationMutation defines model for LocationMutation.
type LocationMutation struct {
	Audit           AuditEvent `json:"audit"`
	Location        Location   `json:"location"`
	PracticeVersion int64      `json:"practiceVersion"`
}

// MediaToken defines model for MediaToken.
type MediaToken struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// MediaTokenRequest defines model for MediaTokenRequest.
type MediaTokenRequest struct {
	SessionId string `json:"sessionId"`
}

// Membership defines model for Membership.
type Membership struct {
	Id            openapi_types.UUID      `json:"id"`
	LocationScope MembershipLocationScope `json:"locationScope"`
	Role          MembershipRole          `json:"role"`
}

// MembershipLocationScope defines model for Membership.LocationScope.
type MembershipLocationScope string

// MembershipRole defines model for Membership.Role.
type MembershipRole string

// NavigationItem defines model for NavigationItem.
type NavigationItem struct {
	Enabled bool             `json:"enabled"`
	Id      NavigationItemId `json:"id"`
	Label   string           `json:"label"`
}

// NavigationItemId defines model for NavigationItem.Id.
type NavigationItemId string

// OperatorCallingTimeline defines model for OperatorCallingTimeline.
type OperatorCallingTimeline struct {
	CallId     openapi_types.UUID             `json:"callId"`
	Entries    []OperatorCallingTimelineEntry `json:"entries"`
	PracticeId openapi_types.UUID             `json:"practiceId"`
	State      OperatorCallingTimelineState   `json:"state"`
	Version    int64                          `json:"version"`
}

// OperatorCallingTimelineState defines model for OperatorCallingTimeline.State.
type OperatorCallingTimelineState string

// OperatorCallingTimelineEntry defines model for OperatorCallingTimelineEntry.
type OperatorCallingTimelineEntry struct {
	AgeSeconds      int64     `json:"ageSeconds"`
	CommandAction   string    `json:"commandAction"`
	CommandAttempts int       `json:"commandAttempts"`
	CommandState    string    `json:"commandState"`
	ErrorCode       string    `json:"errorCode"`
	Kind            string    `json:"kind"`
	OccurredAt      time.Time `json:"occurredAt"`
	OpaqueReference string    `json:"opaqueReference"`
	ReceiptState    string    `json:"receiptState"`
}

// Practice defines model for Practice.
type Practice struct {
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`
	Version int64              `json:"version"`
}

// PracticeAccess defines model for PracticeAccess.
type PracticeAccess struct {
	Id         openapi_types.UUID `json:"id"`
	Locations  []Location         `json:"locations"`
	Membership *Membership        `json:"membership,omitempty"`
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
}

// SignUpEligibilityRequest defines model for SignUpEligibilityRequest.
type SignUpEligibilityRequest struct {
	Email           openapi_types.Email `json:"email"`
	InvitationToken *string             `json:"invitationToken,omitempty"`
}

// SoftphoneLeaseRequest defines model for SoftphoneLeaseRequest.
type SoftphoneLeaseRequest struct {
	SessionId string `json:"sessionId"`
	Takeover  bool   `json:"takeover"`
}

// SoftphoneState defines model for SoftphoneState.
type SoftphoneState struct {
	// ActiveCallId The User's current durable Call, or empty when capacity is free.
	ActiveCallId   string    `json:"activeCallId"`
	Available      bool      `json:"available"`
	LeaseExpiresAt time.Time `json:"leaseExpiresAt"`
	Owner          bool      `json:"owner"`
	SessionId      string    `json:"sessionId"`
}

// SupportMode defines model for SupportMode.
type SupportMode struct {
	ExpiresAt  time.Time          `json:"expiresAt"`
	Id         openapi_types.UUID `json:"id"`
	PracticeId openapi_types.UUID `json:"practiceId"`
	Reason     string             `json:"reason"`
	StartsAt   time.Time          `json:"startsAt"`
}

// WorkspaceSnapshot defines model for WorkspaceSnapshot.
type WorkspaceSnapshot struct {
	Actor            Actor                          `json:"actor"`
	Location         Location                       `json:"location"`
	Membership       *Membership                    `json:"membership,omitempty"`
	Navigation       []NavigationItem               `json:"navigation"`
	PlatformOperator bool                           `json:"platformOperator"`
	Practice         Practice                       `json:"practice"`
	SchemaVersion    WorkspaceSnapshotSchemaVersion `json:"schemaVersion"`
	State            WorkspaceSnapshotState         `json:"state"`
	SupportMode      *SupportMode                   `json:"supportMode,omitempty"`
	Version          int64                          `json:"version"`
}

// WorkspaceSnapshotSchemaVersion defines model for WorkspaceSnapshot.SchemaVersion.
type WorkspaceSnapshotSchemaVersion string

// WorkspaceSnapshotState defines model for WorkspaceSnapshot.State.
type WorkspaceSnapshotState string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// Denied defines model for Denied.
type Denied = ErrorEnvelope

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = ErrorEnvelope

// Unavailable defines model for Unavailable.
type Unavailable = ErrorEnvelope

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	PracticeId openapi_types.UUID `form:"practiceId" json:"practiceId"`
	LocationId openapi_types.UUID `form:"locationId" json:"locationId"`
}

// ReceiveTelnyxWebhookJSONBody defines parameters for ReceiveTelnyxWebhook.
type ReceiveTelnyxWebhookJSONBody map[string]interface{}

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	PracticeId openapi_types.UUID `form:"practiceId" json:"practiceId"`
	LocationId openapi_types.UUID `form:"locationId" json:"locationId"`
}

// InspectSignUpEligibilityJSONRequestBody defines body for InspectSignUpEligibility for application/json ContentType.
type InspectSignUpEligibilityJSONRequestBody = SignUpEligibilityRequest

// RecordCallingDispositionJSONRequestBody defines body for RecordCallingDisposition for application/json ContentType.
type RecordCallingDispositionJSONRequestBody = CallingDispositionRequest

// RequestCallingHangupJSONRequestBody defines body for RequestCallingHangup for application/json ContentType.
type RequestCallingHangupJSONRequestBody = CallingControlRequest

// IssueCallingMediaTokenJSONRequestBody defines body for IssueCallingMediaToken for application/json ContentType.
type IssueCallingMediaTokenJSONRequestBody = MediaTokenRequest

// AcceptCallingOfferJSONRequestBody defines body for AcceptCallingOffer for application/json ContentType.
type AcceptCallingOfferJSONRequestBody = AcceptCallingOfferRequest

// SetCallingReadinessJSONRequestBody defines body for SetCallingReadiness for application/json ContentType.
type SetCallingReadinessJSONRequestBody = CallingReadinessRequest

// AcquireSoftphoneJSONRequestBody defines body for AcquireSoftphone for application/json ContentType.
type AcquireSoftphoneJSONRequestBody = SoftphoneLeaseRequest

// CreateHandoffJSONRequestBody defines body for CreateHandoff for application/json ContentType.
type CreateHandoffJSONRequestBody = CreateHandoffRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationCredentialRequest

// InspectInvitationJSONRequestBody defines body for InspectInvitation for application/json ContentType.
type InspectInvitationJSONRequestBody = InvitationCredentialRequest

// AddLocationJSONRequestBody defines body for AddLocation for application/json ContentType.
type AddLocationJSONRequestBody = AddLocationRequest

// ReceiveTelnyxWebhookJSONRequestBody defines body for ReceiveTelnyxWebhook for application/json ContentType.
type ReceiveTelnyxWebhookJSONRequestBody ReceiveTelnyxWebhookJSONBody

// EnterSupportModeJSONRequestBody defines body for EnterSupportMode for application/json ContentType.
type EnterSupportModeJSONRequestBody = EnterSupportModeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// DiscoverAccess Discover current Practice and Location authorization.
	// (GET /v1/access)
	DiscoverAccess(w http.ResponseWriter, r *http.Request)
	// InspectSignUpEligibility Validate an invitation or provisioned Platform Operator email.
	// (POST /v1/access/sign-up-eligibility)
	InspectSignUpEligibility(w http.ResponseWriter, r *http.Request)
	// GetCallingCall Read the winning User's durable active or disposition Call.
	// (GET /v1/calling/calls/{callId})
	GetCallingCall(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RecordCallingDisposition Resolve the provider-terminated Call without creating a Task.
	// (POST /v1/calling/calls/{callId}/disposition)
	RecordCallingDisposition(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// RequestCallingHangup Commit a provider hangup command without claiming termination.
	// (POST /v1/calling/calls/{callId}/hangup)
	RequestCallingHangup(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// IssueCallingMediaToken Issue a short-lived Telnyx JWT to the current softphone owner.
	// (POST /v1/calling/media-token)
	IssueCallingMediaToken(w http.ResponseWriter, r *http.Request)
	// ListCallingOffers List every current offer the User may accept now.
	// (GET /v1/calling/offers)
	ListCallingOffers(w http.ResponseWriter, r *http.Request)
	// AcceptCallingOffer Atomically claim one current offer and commit its Dial command.
	// (POST /v1/calling/offers/{callId}/accept)
	AcceptCallingOffer(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// SetCallingReadiness Commit the media-owning session's current technical readiness.
	// (PUT /v1/calling/readiness)
	SetCallingReadiness(w http.ResponseWriter, r *http.Request)
	// AcquireSoftphone Acquire, renew, or explicitly take over the User's softphone lease.
	// (POST /v1/calling/softphone/lease)
	AcquireSoftphone(w http.ResponseWriter, r *http.Request)
	// GetEvents Stream disposable version hints for one authorized scope.
	// (GET /v1/events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// CreateHandoff Create one authenticated, idempotent Abita handoff.
	// (POST /v1/handoffs)
	CreateHandoff(w http.ResponseWriter, r *http.Request)
	// AcceptInvitation Atomically activate an invitation for the verified identity.
	// (POST /v1/invitations/accept)
	AcceptInvitation(w http.ResponseWriter, r *http.Request)
	// InspectInvitation Inspect only the scope attached to the presented invitation.
	// (POST /v1/invitations/inspect)
	InspectInvitation(w http.ResponseWriter, r *http.Request)
	// GetOperatorCallingTimeline Read one sanitized durable Call timeline as a Platform Operator.
	// (GET /v1/operator/calls/{callId}/timeline)
	GetOperatorCallingTimeline(w http.ResponseWriter, r *http.Request, callId openapi_types.UUID)
	// AddLocation Add a Location as a Platform Operator in Support Mode.
	// (POST /v1/practices/{practiceId}/locations)
	AddLocation(w http.ResponseWriter, r *http.Request, practiceId openapi_types.UUID)
	// ReceiveTelnyxWebhook Verify and durably receipt one raw Telnyx webhook.
	// (POST /v1/provider/telnyx/webhooks)
	ReceiveTelnyxWebhook(w http.ResponseWriter, r *http.Request)
	// EnterSupportMode Enter time-limited Support Mode for one Practice.
	// (POST /v1/support-mode)
	EnterSupportMode(w http.ResponseWriter, r *http.Request)
	// RevokeSupportMode Revoke the real operator's active Support Mode.
	// (DELETE /v1/support-mode/{supportSessionId})
	RevokeSupportMode(w http.ResponseWriter, r *http.Request, supportSessionId openapi_types.UUID)
	// GetWorkspace Load the authoritative empty workspace snapshot.
	// (GET /v1/workspace)
	GetWorkspace(w http.ResponseWriter, r *http.Request, params GetWorkspaceParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverAccess operation middleware
func (siw *ServerInterfaceWrapper) DiscoverAccess(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectSignUpEligibility operation middleware
func (siw *ServerInterfaceWrapper) InspectSignUpEligibility(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectSignUpEligibility(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCallingCall operation middleware
func (siw *ServerInterfaceWrapper) GetCallingCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCallingCall(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordCallingDisposition operation middleware
func (siw *ServerInterfaceWrapper) RecordCallingDisposition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordCallingDisposition(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestCallingHangup operation middleware
func (siw *ServerInterfaceWrapper) RequestCallingHangup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestCallingHangup(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IssueCallingMediaToken operation middleware
func (siw *ServerInterfaceWrapper) IssueCallingMediaToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IssueCallingMediaToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCallingOffers operation middleware
func (siw *ServerInterfaceWrapper) ListCallingOffers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCallingOffers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptCallingOffer operation middleware
func (siw *ServerInterfaceWrapper) AcceptCallingOffer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptCallingOffer(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCallingReadiness operation middleware
func (siw *ServerInterfaceWrapper) SetCallingReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCallingReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcquireSoftphone operation middleware
func (siw *ServerInterfaceWrapper) AcquireSoftphone(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcquireSoftphone(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Required query parameter "practiceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "practiceId", r.URL.Query(), &params.PracticeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "practiceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "locationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locationId", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locationId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHandoff operation middleware
func (siw *ServerInterfaceWrapper) CreateHandoff(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHandoff(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectInvitation operation middleware
func (siw *ServerInterfaceWrapper) InspectInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperatorCallingTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetOperatorCallingTimeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "callId", r.PathValue("callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperatorCallingTimeline(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddLocation operation middleware
func (siw *ServerInterfaceWrapper) AddLocation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "practiceId" -------------
	var practiceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "practiceId", r.PathValue("practiceId"), &practiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddLocation(w, r, practiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveTelnyxWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveTelnyxWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveTelnyxWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnterSupportMode operation middleware
func (siw *ServerInterfaceWrapper) EnterSupportMode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnterSupportMode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSupportMode operation middleware
func (siw *ServerInterfaceWrapper) RevokeSupportMode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "supportSessionId" -------------
	var supportSessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "supportSessionId", r.PathValue("supportSessionId"), &supportSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "supportSessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSupportMode(w, r, supportSessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Required query parameter "practiceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "practiceId", r.URL.Query(), &params.PracticeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "practiceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		}
		return
	}

	// ------------- Required query parameter "locationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locationId", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locationId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.GetReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/access/sign-up-eligibility", wrapper.InspectSignUpEligibility)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/access", wrapper.DiscoverAccess)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/invitations/inspect", wrapper.InspectInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/invitations/accept", wrapper.AcceptInvitation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspace", wrapper.GetWorkspace)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/support-mode", wrapper.EnterSupportMode)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/support-mode/{supportSessionId}", wrapper.RevokeSupportMode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/practices/{practiceId}/locations", wrapper.AddLocation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.GetEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/handoffs", wrapper.CreateHandoff)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/provider/telnyx/webhooks", wrapper.ReceiveTelnyxWebhook)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/softphone/lease", wrapper.AcquireSoftphone)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/calling/readiness", wrapper.SetCallingReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/media-token", wrapper.IssueCallingMediaToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/offers", wrapper.ListCallingOffers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/offers/{callId}/accept", wrapper.AcceptCallingOffer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/calling/calls/{callId}", wrapper.GetCallingCall)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/calls/{callId}/hangup", wrapper.RequestCallingHangup)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calling/calls/{callId}/disposition", wrapper.RecordCallingDisposition)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/operator/calls/{callId}/timeline", wrapper.GetOperatorCallingTimeline)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F1bc9s4lv4rKO5WzQtlOU66p9Zviq10NCvbGkvp7FRPKgWTRxLGJMAGQNnalP/7FC68g5KoSOok008d",
	"mSB4cM6Hcwf6ixewOGEUqBTe5RePg0gYFaB/vMXhPfyegpDqV8CoBKr/iZMkIgGWhNH+vwSj6m8iWEKM",
	"1b/+m8Pcu/T+q19M3TdPRX/IOeNDuoKIJeC9vLz4Xggi4CRRk3mX3oiucERCxM2Hz7wX37tidB6R4IRU",
	"zJaQUQAhkhxTQdQjRASiDEWMLoAjvMIkwg8RaCqvgRIIT0fjVco5UIlICFQSuUYRDh4FkhXScSqXjBO5",
	"1iR+oOq3Gh5geUpab4gQhC4Q44hYAQccNOE4ykjLuHk6sgaaU4RDiEJIgIZAg7WSsYQ4YRxzEq1RSsty",
	"fvHtx/UOGQQBJPIKRxGhi7v5HHhpw+Aw1KDB0YSzBLgkalvNcSTA95LSn754AoQgjI60SGL8PAa6kEvv",
	"8uL83PdiQrPfr3xPrhPwLj0hOaELTU+2Bu/yt9JEn/Kh7OFfEEjFZBe5Io26UhvgKDKkzhmPsfQuvTQl",
	"odcgzveExFILFGgaKwLv3r0b3o9uf/F87+ru9nZ4Nav8GF57vnc/vLq7vRqNzZMPt4Pb6cfhvX50Oxxe",
	"Tz9fj6aTu+loNrq71cOnd+Nf9eN3d+Px3cfPHyaf74d//zBS73xqoSoVZbIGV1fDifn6YHw/HFz/4/PV",
	"eDC60X8Z/t9kZD4/uh2OR7+M3o6HjnnrojAf8TN2ZcxoE4wQ10QEbAV83VEeOJCMb9sMAz3oxfeSCEsl",
	"t7sEOLYvWoIeGIsAUz2K40CSwHyASIjFtg9M7BtmLWoOOyvmHK8b7DFEO8gpf9vNK0t0Bw5BjElUAaz5",
	"iwsbqflSwZXimflDgZr3H24GCoGT8WD27u7+5vPdZHg/mN3d74AO+xm/SolzwWE4ZkYB7qddHmFd0yuv",
	"tuoV36M4hs7qSPEvSRiX07JG26ImGqypzeDrFViKnBxKQyKHq8xgdNo5xFiUxjo0PqcbwBBwUEZ0ICsr",
	"DLGEniQxuLBFdlOaGf531LEcsGhZxNcLQw+p8KJCn++SluVqTlmZV27xaSfl/3EmjI4SXEG2P7bpqHxc",
	"JuCdtWZk39xdH5a/VdWEvhdD/ABcLEmybZabYmRn3b2rxi4h5YaFW1+bloa2avVs6jLnHPS74GD9E/Wf",
	"ro4JoxSCjpsyBBxGhEKHN4hIIry+tQqy8RyeE03FDYQEz9gjaFxWXc+7BP+eApLqKZJLnPnxcwLGh4dn",
	"HEj0ER7uZ1coVjOhCBZozrh+HFjvP4gwic9cVGZUTCWez8ewMLu/SsUwTqTycCWJ0Awiun6uk8EoIKFm",
	"0F+3+9hSQcSGz++o6zJ0jLoNb+W9shFTlvLA/ThZMrrhyaY3uynlhLMVCYHPgMeE4lYzY1Tkhu9yCBgP",
	"1Y8t29Jum/t8vMv9/uN8bh1E64ij1VqtgAvLp5y/hMqf33ja6yCxWkPhcxAqYQHcbbIqNqoEshqEMhaV",
	"1EAGkiokqru+grPG2mpSdW5Fp5Zww6ZgzCZtyajkLPqmw09L6jURCTP5lP3IZakMWFzB9R4xYGXNe63R",
	"zynZsFodZndc4OFN0jeqjfdxdDfM155t+J400lcompISy/TaDrpDQ3RMOu/D3A3eyR+u7Idt2QEz4waa",
	"7wGHhIIQ+6kQnIaEqTnWbhe6koxsPo5JwJk2Dxvm4LAgQgI3idbmc6tI3gOO5HK9ccwhNXOFsOZS/DJv",
	"GkSWObNROiWnpYNY5phEKYcrG4Vs3+Cj29nw9jr3YO6vjf+iM3jKFgxGY6f+d+TqWhbEqMSBVP+BZzmi",
	"SdoVajXVXBfiFp1ZT9q0e7SlkW9aB3aYuK5tt77Q1KelV35yvPLi4reOMN5jGrL5fL+9HRiRbdVHDslq",
	"SwlxwiTQYP2/jbzZLgmwjja0ow0UWh5XeQb+a3RCu0WqfKXBEz9nsWvHDKkEXsoR7CfEMOWanBtCU2n+",
	"FONnY3Av3pxvNr9fkUKrQ3Zvfua5r/pKnDyrVKo65rbVu523SIuCDRjnEJXw2xgRgxB40RarSr5us5o1",
	"ZmkSiunqny5P1uRYbS7DAhdjrSLpytLnhHAQR0jtCpJcg5DtGQGX51h7yS/R51yzttUdl8xZVDGsavfi",
	"qIcTUopKe4QuOAhh4B1pXuxWX2OPHQpmmhbXykZ0RaRmwlVePd5PvcgsK1fWnz/9XNnvry+2UWxm2Uzp",
	"hMOKwNPxClZ7gPWR0LAsncn94Go2uhp+Ht3+OpoNbI5nl6pWYTemAasWxwbjsed70+HYpJg2vXuYpHrn",
	"DJ0Z3hq81rfE4PpmpPgynQ3evdsOZ83korxXrNWFl3IBo0sEtttSqXuJLl3TWmPLKLxJ5V51mjQkW12y",
	"Uh2vhI4umMiE+uuGwH1LsJ5/tjmbb5fh4k812X9cY5Nrr13U0zZzURD+TScPbyols8Pvka/RY1+pKTRB",
	"eo46GS5G3OIVWRg3SULcFWxUeVQtCQlSMQoSi8esfaUXgPLqvVI5QujkgJT6n07ljh8g2lHrmLF+Tp5r",
	"3VnN0KYYZiSGLEd6nN4loJKTDg0wLQQOqeTrA9irb7OV6kAZ0rxHqtpbUMthFjLpABDD/47WagFTCBgN",
	"xeaFnbtiz4DFMabhoL23JBshJcSJabzdacppBoEmVlUE1Jo2y/y9xgMW6Dpyp3o505Xre5gDB9petASS",
	"yDZ63Z5SfeLyqupcrbGkydIaDX5ZpJV1u5A0KTVQnMwbO2y1gZrqwabsf61hT601iu7m3uVvO7eNdGLP",
	"t9BC0+LruRTKpxffm5IF/ZAMI7IgDyQicr2fi9QezZX8pdcXrqQqyQPJ2UFCVvNhFxymbC51jngMWMCp",
	"fUHfk/gR2Ar4DrmjcjEjf23jmnJN1Lm1rEi1No8IfBDA/yLyXpww5cp9QeoVHzGOQLfXPC2BogAnOCBS",
	"d5fPOYCzZ2ZL1SlSghl2DxfYEwW+Q31p9wpSjZLsE+UV+FX+OaVT7Tn7JhJ0B+y9lJjLDiRurRnnGeV8",
	"5m2h3UfGH0WCA5hSnIglk0dtLN8nXt+3EZLmQdDOxqQWN7kc8uN1V+q/lZISmQ9/cX7xc+/8r72LN62J",
	"1IrPP7yZzP7hHrpnA+fB3I7qGstOe+bGb2gO9Soi3alRVGuvIOVErqfq0wayD4A58EFqEuDm17tsVX/7",
	"OPOsMLRQ9dNiJy6lTIxS5CsSwFvzuDmNcVR7dlgvS7NsmfdFW/M5a5qSQZAqyzDRKXdk3DGEaYjepzGm",
	"NpxBiu98jgMQ6InIJZowIRccpn8fF6e8/NwG2W5O6xab6axHLHz9K9RtWHpwlsxHS0KlOPunWo0kUtmh",
	"OnGTUUm0lwV+/2pCA6A4Id6l9/rs/Oy1kiOWSy2X/lJXJfoRWWl8LkArI6blay2Q9wvIMVkBzUoMpbOI",
	"F+fnBzsXZgskjgNhE84084lAPKWU0MVZBWje5W+f1O9sNTzr/mhbTt6m8ses5z473sZTqgWcH3MjIBDm",
	"WvShORz40/nrtg/llPfLx/ScjFm96uM8nnByJTvlZMOOI/KlfqpqwyHKbNNlGwnNOYtLW0xz6M35q504",
	"VDljqd/bgbP2+OjegkjjGPN1ib+5W5oZIr3rM+ObLdUcujAoL4TXF2RBe2nSgyL0UTQlTDgkOqIigUA2",
	"giXPGAgQ8i0z2+QgYm0Nyl6qJknyFF6OCK9mja/lJPEKOJkTCHs6+EKWt0rJGPbaA8QngUlpv5ZB8yuO",
	"iPJNEaaoCDlVDKNrv0rbQ4gm1iqjzCwjvaICPYGxVfq/ov/FZPVeNinI8mEPZS44jkECFzoLQRQHlQnJ",
	"EhqXRaKwKme/JLNtB5w+HRET5eW4DhzbTQehDhLRU+agf0f6RZk0fTTkiWgLmUXBmedhwj4FnbBo9NbL",
	"3YaTfumFdm1jegubveQnhc/htVp7c/yJ1doWCF9bMUtzQiEyQLaN8BbG59vxVbpb4nTIf3P+P9uH57dN",
	"HGKrCBatQO+WvIfGMk7mOoDIJUulOVul9hNGMywet26WJaaLNNm0TzR7rTjfm9E/xB6pnXXZaX9cnGp/",
	"GEbraI1KHX8RKSE8+4FhfqUXiXCOcWSwmUWfBcQjTGIFcVkcb2riXB927OU9Di0+pxApWFFUTlAdA3fN",
	"FokT6+TSCh2Qmy4Zlz0VWYfogbMnAdyeGK1dsvKnZs4gq+GDMBIl1tmUyd8+zpBklUO2IisjIJ3nbkKW",
	"zedaobb4uWMiKreuHDXqbRzqcSBmiHlEQMhedmCoNydcyDz+xcaF07R+R66pWi4CFevnotNr0ML8oLcF",
	"XiOsb8FBlD21CbIwsmZsuxpq3qjznZvY9huNTqzyWu8qcmVxMitrZYtpoAMQeFZfJxJFTF8/xfUM37gq",
	"/Mo9MJAsJgpfa2Nu9Qn+6m5QJtk4JohIga4JjjJT3dwRPM9gqk2QOvbANI/iq9nOo/l/jbN/J4Zmraq8",
	"Ia0YAtemJWcYjpCuhvzYGLQOodK6xpljTzpTYEvIpZK5hGBJFVxRjrMmBHPz29d1503aWEMgl8+xEpDO",
	"TolvFoQ170UsSfKDq0ADAx9xoPDkly1BtEYSPwLSCXJZtHAUPNIQKzAIq+xqzLYM5tCMcJv931Pg68Lu",
	"1+r5+9p+3z175QjfMfOjEp6l4UxPSA44rsK2PmEDmW9ZSkMIUWOeMzSiRBp7pK/y0ZUKGlqnjoP9c3Zv",
	"I8K05rPmGVXEYQ4yWJ79k34/yJ1qLpRLs7bUaiqz+t4dBVJc5JFFwJISXpfmwJtoV5KVE7bHMtSuU7w7",
	"KchXh6uK2hU68GcvX1I+YQS9VACajibIsu7PSLlaJ/pS74f47dNLpXZkhJ3jMl+cj/JzwxINHojEJRZb",
	"uBa1JrFjrFVU3Y6E3U2HDE8dA1UuxnPdq5s3RWkt6VALP2wGpxTn6IpTs3iZXZWWlV/zm5Ld8COmir21",
	"zP2fBMCdStwToKFpUMoG/+HlbCsqxKhy+JZgtgPCUuJgqRwPZmsyIIBKBY0y7RYczBa564UXWTp51OYU",
	"th1W+gFK3G1LcyWmsfLmlDrKKwO6HMD44zxiT2hJhGR8/b0Vv/WdiPnSyl3fKMMGwgLhZr9EAa78juP+",
	"lyIoeOlXzki0mMHiOuCd4HSgmONY+cbm5cYn9hMbB5s3Jhjz/qnYDreGNyQ/el4xDBEutY858Y0IRba7",
	"GN2wEMp4NwqgL3WVpf8ED0vGHsXGPg8gKzBVmY9m+FdYXHfbu9kF9c7iHfD3ptnGe2/aa61CWBe1X8S4",
	"TUxrdWGo3DsFeNi+L+UbrU0/sCXbdglrLcfxU1YWswIrJGobznux7Th3S7F+G9CRfKa2S4dOrEuqVyM3",
	"279Ma1Rth/zASkOLRRvFXkRiovBfXnyez8haVN3o6n+pXzL+YnZfBOZ0RF1xrNgjVDG33Uw67jE/pP/l",
	"0BcVTnBNdPhduUKKYvv/m8ERytzlv4isBdBtCfIM3Sb/OT+59B+VV91f8TRPem3uPi3SpMK+8D2V+Znt",
	"QK2mfu1pS9fKGimt8jEhm88CvsogVut4hCRi61hnqVMlIQjR+9lsMkWMkwVRXnjKI3vOR1z2+zghZ1gf",
	"mzmDZxwnagGfXv4dAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
