package humancalling

const StaleCallLegCandidateQueryForTest = staleCallLegCandidateQuery

const NextCallLegCommandQueryForTest = nextCallLegCommandQuery

const InterruptedCallLegCommandQueryForTest = interruptedCallLegCommandQuery
