package architecture

import (
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var allowedCommentPrefixes = []string{"//go:", "// +build", "//line ", "//export ", "//nolint"}

func allowedComment(text string) bool {
	for _, prefix := range allowedCommentPrefixes {
		if strings.HasPrefix(text, prefix) {
			return true
		}
	}
	return false
}

func trackedGoFiles(t *testing.T) []string {
	t.Helper()
	command := exec.Command("git", "ls-files", "--cached", "--others", "--exclude-standard", "--", "backend/*.go", "deploy/*.go")
	command.Dir = repositoryRoot(t)
	output, err := command.Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			t.Fatalf("git ls-files: %v\n%s", err, exitErr.Stderr)
		}
		t.Fatalf("git ls-files: %v", err)
	}
	var files []string
	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		if line != "" {
			files = append(files, line)
		}
	}
	if len(files) == 0 {
		t.Fatal("git ls-files returned no Go files")
	}
	return files
}

func commentViolations(fset *token.FileSet, file *ast.File) []string {
	if ast.IsGenerated(file) {
		return nil
	}
	var violations []string
	for _, group := range file.Comments {
		for _, comment := range group.List {
			if !allowedComment(comment.Text) {
				violations = append(violations, fmt.Sprintf("%s: code comments are not allowed; say it in names, types, or tests instead", fset.Position(comment.Slash)))
			}
		}
	}
	return violations
}

func TestGoSourceHasNoComments(t *testing.T) {
	root := repositoryRoot(t)
	fset := token.NewFileSet()
	for _, name := range trackedGoFiles(t) {
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		file, err := parser.ParseFile(fset, name, content, parser.ParseComments)
		if err != nil {
			t.Errorf("parse %s: %v", name, err)
			continue
		}
		for _, violation := range commentViolations(fset, file) {
			t.Error(violation)
		}
	}
}

func TestCommentViolationsAllowDirectivesAndGeneratedFiles(t *testing.T) {
	for _, test := range []struct {
		source string
		want   int
	}{
		{"//go:build linux\n\npackage p\n\n//go:generate echo\n//go:embed x\nvar x string\n", 0},
		{"// Code generated by tool. DO NOT EDIT.\n\npackage p\n\n// Doc.\nfunc F() {}\n", 0},
		{"package p\n\n// Doc.\nfunc F() {}\n", 1},
		{"package p\n\nfunc F() {\n\tx := 1 /* inline */\n\t_ = x // trailing\n}\n", 2},
		{"package p\n\nconst sql = `SELECT 1 -- not a Go comment // /* */`\n", 0},
		{"package p\n\n//go :generate spaced is prose\nvar x int\n", 1},
	} {
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, "fixture.go", test.source, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		if got := commentViolations(fset, file); len(got) != test.want {
			t.Errorf("commentViolations(%q) = %v, want %d violations", test.source, got, test.want)
		}
	}
}
